export const CONTINENT_MAP: Record<string, string> = {
  Deutschland: "Europa",
  Österreich: "Europa",
  Schweiz: "Europa",
  Frankreich: "Europa",
  Spanien: "Europa",
  Italien: "Europa",
  Niederlande: "Europa",
  Belgien: "Europa",
  "Vereinigtes Königreich": "Europa",
  Schweden: "Europa",
  Norwegen: "Europa",
  Dänemark: "Europa",
  Finnland: "Europa",
  Polen: "Europa",
  Tschechien: "Europa",
  Ungarn: "Europa",
  Portugal: "Europa",
  Kroatien: "Europa",
  Griechenland: "Europa",
  Türkei: "Europa",
  Russland: "Europa",
  Ukraine: "Europa",
  Slowakei: "Europa",
  Slowenien: "Europa",
  Serbien: "Europa",
  Bulgarien: "Europa",
  Rumänien: "Europa",
  Luxemburg: "Europa",
  Irland: "Europa",
  Island: "Europa",
  Litauen: "Europa",
  Lettland: "Europa",
  Estland: "Europa",
  Weißrussland: "Europa",
  Nordmazedonien: "Europa",
  Bosnien: "Europa",
  Montenegro: "Europa",
  Albanien: "Europa",
  Malta: "Europa",
  Zypern: "Europa",
  Germany: "Europe",
  Austria: "Europe",
  Switzerland: "Europe",
  France: "Europe",
  Spain: "Europe",
  Italy: "Europe",
  Netherlands: "Europe",
  Belgium: "Europe",
  "United Kingdom": "Europe",
  Sweden: "Europe",
  Norway: "Europe",
  Denmark: "Europe",
  Finland: "Europe",
  Poland: "Europe",
  "Czech Republic": "Europe",
  Hungary: "Europe",
  Portugal: "Europe",
  Croatia: "Europe",
  Greece: "Europe",
  Turkey: "Europe",
  Russia: "Europe",
  Ukraine: "Europe",
  Slovakia: "Europe",
  Slovenia: "Europe",
  Serbia: "Europe",
  Bulgaria: "Europe",
  Romania: "Europe",
  Luxembourg: "Europe",
  Ireland: "Europe",
  Iceland: "Europe",
  Lithuania: "Europe",
  Latvia: "Europe",
  Estonia: "Europe",
  "United States": "North America",
  "USA": "North America",
  Canada: "North America",
  Mexico: "North America",
  "Vereinigte Staaten": "Nordamerika",
  Kanada: "Nordamerika",
  Mexiko: "Nordamerika",
  Brazil: "South America",
  Brasilien: "Südamerika",
  Argentina: "South America",
  Argentinien: "Südamerika",
  Chile: "South America",
  Colombia: "South America",
  Peru: "South America",
  Uruguay: "South America",
  Venezuela: "South America",
  Japan: "Asia",
  "South Korea": "Asia",
  "Südkorea": "Asien",
  China: "Asia",
  Taiwan: "Asia",
  "Hong Kong": "Asia",
  Singapore: "Asia",
  Singapur: "Asien",
  Indonesia: "Asia",
  Indonesien: "Asien",
  Malaysia: "Asia",
  Thailand: "Asia",
  Philippines: "Asia",
  Philippinen: "Asien",
  India: "Asia",
  Indien: "Asien",
  Australia: "Oceania",
  Australien: "Ozeanien",
  "New Zealand": "Oceania",
  Neuseeland: "Ozeanien",
  "South Africa": "Africa",
  Südafrika: "Afrika",
  Morocco: "Africa",
  Marokko: "Afrika",
  Egypt: "Africa",
  Ägypten: "Afrika",
};

export const CONTINENT_ORDER_DE = [
  "Europa", "Nordamerika", "Südamerika", "Asien", "Ozeanien", "Afrika",
];
export const CONTINENT_ORDER_EN = [
  "Europe", "North America", "South America", "Asia", "Oceania", "Africa",
];

export function getContinent(country: string): string {
  return CONTINENT_MAP[country] ?? "Other";
}

export const COUNTRIES_DE = [
  "Deutschland", "Österreich", "Schweiz", "Niederlande", "Belgien",
  "Luxemburg", "Frankreich", "Spanien", "Italien", "Portugal",
  "Vereinigtes Königreich", "Irland", "Schweden", "Norwegen", "Dänemark",
  "Finnland", "Polen", "Tschechien", "Slowakei", "Ungarn", "Rumänien",
  "Bulgarien", "Griechenland", "Kroatien", "Slowenien", "Serbien",
  "Türkei", "Russland", "Ukraine",
  "Vereinigte Staaten", "Kanada", "Mexiko",
  "Brasilien", "Argentinien", "Chile",
  "Japan", "Südkorea", "China", "Taiwan", "Hong Kong", "Singapur", "Australien", "Neuseeland",
];

export const COUNTRIES_EN = [
  "Germany", "Austria", "Switzerland", "Netherlands", "Belgium",
  "Luxembourg", "France", "Spain", "Italy", "Portugal",
  "United Kingdom", "Ireland", "Sweden", "Norway", "Denmark",
  "Finland", "Poland", "Czech Republic", "Slovakia", "Hungary", "Romania",
  "Bulgaria", "Greece", "Croatia", "Slovenia", "Serbia",
  "Turkey", "Russia", "Ukraine",
  "United States", "Canada", "Mexico",
  "Brazil", "Argentina", "Chile",
  "Japan", "South Korea", "China", "Taiwan", "Hong Kong", "Singapore", "Australia", "New Zealand",
];
