// ─── Types ─────────────────────────────────────────────────────────────────

export type CardSlot = {
  name: string;
  count: number;
  roleDe: string;
  roleEn: string;
};

export type LandSlot = {
  name: string;
  count: number;
};

export type Archetype = {
  key: string;
  format?: string;
  deckSize?: number;
  commanderSlot?: CardSlot;
  labelDe: string;
  labelEn: string;
  colors: string[];
  colorHex: string;
  icon: string;
  tagsDe: string[];
  tagsEn: string[];
  summaryDe: string;
  summaryEn: string;
  whyDe: string;
  whyEn: string;
  slots: CardSlot[];
  lands: LandSlot[];
};

// ─── Modern Archetypes ─────────────────────────────────────────────────────

const MODERN_ARCHETYPES: Archetype[] = [
  {
    key: "weisser-aufmarsch",
    labelDe: "Weißer Aufmarsch", labelEn: "White Weenie",
    colors: ["W"], colorHex: "#f8d878", icon: "shield-checkmark-outline",
    tagsDe: ["Aggro", "Einfach", "Weiß"], tagsEn: ["Aggro", "Beginner", "White"],
    summaryDe: "Günstige weiße Kreaturen überwältigen den Gegner bevor er sich sammeln kann. Eins der ältesten und bewährtesten Decks in Magic.",
    summaryEn: "Cheap white creatures overwhelm the opponent before they can set up. One of the oldest and most proven strategies in Magic.",
    whyDe: "Das Deck nutzt den Tempo-Vorteil: 1-Mana-Kreaturen kommen früh ins Spiel, Verstärker wie 'Luminarch Aspirant' lassen sie wachsen, und Sprüche wie 'Path to Exile' räumen Blocker aus dem Weg. 'Thalia' bremst das gegnerische Deck zusätzlich. Das Ergebnis: Der Gegner stirbt oft an Turn 4-5, bevor er seinen Plan umsetzen kann.",
    whyEn: "The deck uses tempo advantage: 1-mana creatures come in early, enhancers like 'Luminarch Aspirant' make them grow, and spells like 'Path to Exile' clear blockers. 'Thalia' slows down the opponent's deck. Result: the opponent often dies on turn 4-5 before they can execute their plan.",
    slots: [
      { name: "Thalia, Guardian of Thraben",  count: 4, roleDe: "Kern-Störer: erschwert Zaubersprüche des Gegners",         roleEn: "Core disruptor: taxes opponent's spells" },
      { name: "Luminarch Aspirant",            count: 4, roleDe: "Zähler-Motor: stärkt jede Runde eine Kreatur",             roleEn: "Counter engine: buffs a creature every turn" },
      { name: "Adanto Vanguard",               count: 4, roleDe: "Unblockbarer Angreifer mit Schutz",                       roleEn: "Evasive attacker with protection" },
      { name: "Selfless Spirit",               count: 3, roleDe: "Schutz vor Massenentfernung",                              roleEn: "Protection from board wipes" },
      { name: "Knight of the White Orchid",    count: 4, roleDe: "Rampe + 2/2 Körper für 2 Mana",                           roleEn: "Ramp + 2/2 body for 2 mana" },
      { name: "Benalish Marshal",              count: 4, roleDe: "Verstärkt alle Kreaturen um +1/+1",                       roleEn: "Buffs all creatures +1/+1" },
      { name: "History of Benalia",            count: 4, roleDe: "Generiert 2 Ritter + Massenbuff",                         roleEn: "Generates 2 Knights + mass buff" },
      { name: "Path to Exile",                 count: 4, roleDe: "Beste weiße Einzelentfernung",                            roleEn: "Best white single removal" },
      { name: "Brave the Elements",            count: 3, roleDe: "Schutz/Durchbruch für alle weißen Kreaturen",            roleEn: "Protection/evasion for all white creatures" },
      { name: "Gideon, Ally of Zendikar",      count: 2, roleDe: "Token-Maschine + Massenbuff als Planeswalker",            roleEn: "Token engine + mass buff as planeswalker" },
    ],
    lands: [{ name: "Plains", count: 20 }],
  },
  {
    key: "blaue-kontrolle",
    labelDe: "Blaue Kontrolle", labelEn: "Blue Control",
    colors: ["U"], colorHex: "#0e68ab", icon: "water-outline",
    tagsDe: ["Kontrolle", "Mittel", "Blau"], tagsEn: ["Control", "Intermediate", "Blue"],
    summaryDe: "Kontroll-Strategie: Gegnerische Pläne mit Gegenzaubern stoppen, Karten ziehen und dann mit mächtigen Kreaturen oder Planeswalker gewinnen.",
    summaryEn: "Control strategy: stop opponent's plans with counterspells, draw cards, then win with powerful threats.",
    whyDe: "Kontrolle funktioniert durch Ressourcen-Überlegenheit. Gegenzauber verhindern die wichtigsten Karten des Gegners, Karten-Zieher garantieren dass man immer die richtige Antwort in der Hand hat. 'Teferi' sperrt den Gegner komplett, während 'Jace' den Friedhof als zweite Bibliothek nutzt. Das Deck verliert selten durch Ressourcen, gewinnt aber langsam.",
    whyEn: "Control works through resource superiority. Counterspells prevent the opponent's best cards, card draw ensures you always have the right answer. 'Teferi' locks the opponent completely, while 'Jace' uses the graveyard as a second library. The deck rarely runs out of resources but wins slowly.",
    slots: [
      { name: "Counterspell",                  count: 4, roleDe: "Kern-Gegenzauber: stoppt alles",                          roleEn: "Core counterspell: stops everything" },
      { name: "Cryptic Command",               count: 3, roleDe: "Flexibler Mehrzweck-Gegenzauber",                         roleEn: "Flexible multi-mode counterspell" },
      { name: "Brainstorm",                    count: 4, roleDe: "Karten-Qualität: findet die richtige Karte",              roleEn: "Card quality: finds the right card" },
      { name: "Ponder",                        count: 4, roleDe: "Bibliothek manipulieren + Kartenqualität",                roleEn: "Library manipulation + card quality" },
      { name: "Fact or Fiction",               count: 3, roleDe: "Karten-Vorteil: bis zu 4 Karten auf einen Schlag",       roleEn: "Card advantage: up to 4 cards at once" },
      { name: "Snapcaster Mage",               count: 4, roleDe: "Wiederholt Zaubersprüche aus dem Friedhof",               roleEn: "Recasts spells from graveyard" },
      { name: "Vendilion Clique",              count: 3, roleDe: "Handstörer + Flugbedrohung",                              roleEn: "Hand disruption + flying threat" },
      { name: "Teferi, Hero of Dominaria",     count: 3, roleDe: "Kern-Planeswalker: zeichnet Karten + räumt Permanente auf", roleEn: "Core planeswalker: draws + cleans up permanents" },
      { name: "Jace, the Mind Sculptor",       count: 2, roleDe: "Stärkster Planeswalker: komplette Kontrolle der Bibliothek", roleEn: "Strongest planeswalker: full library control" },
      { name: "Murdering of Crows",            count: 2, roleDe: "Massenentfernung",                                        roleEn: "Board wipe" },
    ],
    lands: [{ name: "Island", count: 24 }],
  },
  {
    key: "roter-brand",
    labelDe: "Roter Brand", labelEn: "Red Burn",
    colors: ["R"], colorHex: "#e67e22", icon: "flame-outline",
    tagsDe: ["Aggro", "Einfach", "Rot"], tagsEn: ["Aggro", "Beginner", "Red"],
    summaryDe: "Schnellstes Deck: Feuerbälle direkt ins Gesicht bis der Gegner bei 0 Leben ist. Gewinnt oft an Turn 3.",
    summaryEn: "Fastest deck: direct damage spells to the face until the opponent hits 0 life. Wins as early as turn 3.",
    whyDe: "Brand-Decks zählen alle Schadensquellen. Ein typisches Eröffnungsspiel: T1 'Goblin Guide', T2 'Eidolon of the Great Revel', T3 'Lightning Bolt' + 'Skullcrack' = der Gegner hat 10 Schaden und kein Gegenmittel. 'Eidolon' ist brutal: er schadet dem Gegner für jeden Spruch den er wirkt. 'Skullcrack' verhindert Lebenspunkte-Gewinne die sonst den Plan stoppen würden.",
    whyEn: "Burn decks count all damage sources. A typical opening: T1 'Goblin Guide', T2 'Eidolon of the Great Revel', T3 'Lightning Bolt' + 'Skullcrack' = opponent has 10 damage and no answer. 'Eidolon' is brutal: it damages the opponent for every spell they cast. 'Skullcrack' prevents life gain that would otherwise stop the plan.",
    slots: [
      { name: "Lightning Bolt",                count: 4, roleDe: "Beste Brand-Karte: 3 Schaden für 1 Mana",                roleEn: "Best burn spell: 3 damage for 1 mana" },
      { name: "Lava Spike",                    count: 4, roleDe: "Direktschaden: immer aufs Gesicht",                      roleEn: "Direct damage: always to the face" },
      { name: "Rift Bolt",                     count: 4, roleDe: "3 Schaden, aufgesetzt für 1 Mana",                       roleEn: "3 damage, suspend for 1 mana" },
      { name: "Shard Volley",                  count: 4, roleDe: "4 Schaden für 1 Mana (opfert Land)",                     roleEn: "4 damage for 1 mana (sacrifices land)" },
      { name: "Goblin Guide",                  count: 4, roleDe: "1-Mana-2/2 Hast: aggressivste Kreatur",                  roleEn: "1-mana 2/2 haste: most aggressive creature" },
      { name: "Eidolon of the Great Revel",    count: 4, roleDe: "Schadet Gegner für jeden Spruch den sie wirken",         roleEn: "Damages opponent for each spell they cast" },
      { name: "Skullcrack",                    count: 4, roleDe: "Verhindert Lebenspunkte-Gewinne des Gegners",            roleEn: "Prevents opponent's life gain" },
      { name: "Light Up the Stage",            count: 4, roleDe: "Kartenvorteil für Brand-Decks",                          roleEn: "Card advantage for burn decks" },
      { name: "Monastery Swiftspear",          count: 4, roleDe: "Hast + Prowess: wächst mit jedem Spruch",                roleEn: "Haste + Prowess: grows with every spell" },
    ],
    lands: [
      { name: "Sacred Foundry", count: 4 },
      { name: "Mountain", count: 16 },
    ],
  },
  {
    key: "gruener-stompy",
    labelDe: "Grüner Stompy", labelEn: "Green Stompy",
    colors: ["G"], colorHex: "#16a34a", icon: "leaf-outline",
    tagsDe: ["Midrange", "Einfach", "Grün"], tagsEn: ["Midrange", "Beginner", "Green"],
    summaryDe: "Mana beschleunigen und dann mit riesigen Kreaturen den Gegner überrennen. Kein Plan B nötig — sie sind einfach zu groß.",
    summaryEn: "Accelerate mana then run over the opponent with giant creatures. No Plan B needed — they're just too big.",
    whyDe: "Stompy nutzt Mana-Effizienz: Elfen und Amulett beschleunigen auf 6-8 Mana schon in Runde 3-4. Dann kommen 'Thragtusk', 'Primeval Titan' oder 'Craterhoof Behemoth' — Kreaturen die das Spiel alleine gewinnen können. 'Rancor' ist unverzichtbar: gibt Trampeln und kehrt aus dem Friedhof zurück. Das Deck ist linear aber extrem effizient.",
    whyEn: "Stompy uses mana efficiency: elves and artifacts ramp to 6-8 mana by turn 3-4. Then come 'Thragtusk', 'Primeval Titan' or 'Craterhoof Behemoth' — creatures that can win the game alone. 'Rancor' is essential: gives trample and returns from the graveyard. The deck is linear but extremely efficient.",
    slots: [
      { name: "Llanowar Elves",               count: 4, roleDe: "Turn-1-Rampe: gibt grünes Mana",                          roleEn: "Turn-1 ramp: produces green mana" },
      { name: "Elvish Mystic",                count: 4, roleDe: "Zweiter Satz Mana-Elfen",                                  roleEn: "Second set of mana elves" },
      { name: "Burning-Tree Emissary",        count: 4, roleDe: "Kostenloses Tempo: zahlt sich selbst zurück",             roleEn: "Free tempo: pays for itself" },
      { name: "Steel Leaf Champion",          count: 4, roleDe: "3/4 Unrestricted für 3 grünes Mana",                     roleEn: "Powerful 3/4 for 3 green mana" },
      { name: "Leatherback Baloth",           count: 4, roleDe: "4/5 für 3 Mana: enormes Preis-Leistungs-Verhältnis",     roleEn: "4/5 for 3 mana: enormous value" },
      { name: "Rancor",                       count: 4, roleDe: "Trampel-Verstärker der aus dem Friedhof zurückkommt",    roleEn: "Trample enhancer that returns from graveyard" },
      { name: "Aspect of Hydra",              count: 4, roleDe: "Kraftverstärker: +X/+X wobei X die grüne Hingabe ist",   roleEn: "Power boost: +X/+X where X is green devotion" },
      { name: "Vines of Vastwood",            count: 4, roleDe: "Hexenschutz + Größenbonus als Reaktion",                 roleEn: "Hexproof + size boost in response" },
      { name: "Dungrove Elder",               count: 4, roleDe: "Wächst mit jedem Wald im Spiel",                         roleEn: "Grows with every forest in play" },
    ],
    lands: [
      { name: "Nykthos, Shrine to Nyx", count: 4 },
      { name: "Forest", count: 20 },
    ],
  },
  {
    key: "zombie-stamm",
    labelDe: "Zombie-Stamm", labelEn: "Zombie Tribal",
    colors: ["B"], colorHex: "#7c3aed", icon: "skull-outline",
    tagsDe: ["Stamm", "Mittel", "Schwarz"], tagsEn: ["Tribal", "Intermediate", "Black"],
    summaryDe: "Die Untoten stehen immer wieder auf. Ein Zombie-Deck nutzt Synergien zwischen Zombie-Kreaturen und Verstärkern um eine unaufhaltsame Horde zu erschaffen.",
    summaryEn: "The undead always rise again. A Zombie deck leverages synergies between zombie creatures and lords to create an unstoppable horde.",
    whyDe: "Lords wie 'Lord of the Undead' und 'Death Baron' geben allen Zombies +1/+1, was bei einer Horde schnell eskaliert. 'Gravecrawler' ist der beste Zombie: er kostet 1 Mana und kommt immer wieder aus dem Friedhof zurück. 'Carrion Feeder' kombiniert mit Gravecrawler für unendliche Sterbe-Trigger. 'Cryptbreaker' schafft Tokens und zeichnet Karten — der Motor des Decks.",
    whyEn: "Lords like 'Lord of the Undead' and 'Death Baron' give all zombies +1/+1, which escalates quickly with a horde. 'Gravecrawler' is the best zombie: it costs 1 mana and returns from the graveyard repeatedly. 'Carrion Feeder' combos with Gravecrawler for infinite death triggers. 'Cryptbreaker' creates tokens and draws cards — the engine of the deck.",
    slots: [
      { name: "Gravecrawler",                 count: 4, roleDe: "Kern-Zombie: kehrt immer aus dem Friedhof zurück",        roleEn: "Core zombie: always returns from graveyard" },
      { name: "Cryptbreaker",                 count: 4, roleDe: "Token-Generator + Karten-Zieher",                         roleEn: "Token generator + card draw engine" },
      { name: "Diregraf Colossus",            count: 4, roleDe: "Wächst mit jedem Zombie; erschafft Token beim Beschwören", roleEn: "Grows with each zombie; creates tokens on ETB" },
      { name: "Death Baron",                  count: 4, roleDe: "Lord: +1/+1 + Todesberührung für alle Zombies",           roleEn: "Lord: +1/+1 + deathtouch for all zombies" },
      { name: "Lord of the Undead",           count: 4, roleDe: "Lord: +1/+1 + Zombie aus Friedhof zurückholen",           roleEn: "Lord: +1/+1 + return zombie from graveyard" },
      { name: "Undead Augur",                 count: 4, roleDe: "Karten-Zieher: zieht wenn ein Zombie stirbt",             roleEn: "Card draw: draws when a zombie dies" },
      { name: "Carrion Feeder",               count: 4, roleDe: "Opfer-Outlet + wächst mit jedem Opfer",                  roleEn: "Sacrifice outlet + grows with each sacrifice" },
      { name: "Geralf's Messenger",           count: 4, roleDe: "Unsterblicher Zombie: verliert beim Tod 2 LP",            roleEn: "Undying zombie: deals 2 damage on death" },
    ],
    lands: [
      { name: "Swamp", count: 20 },
      { name: "Urborg, Tomb of Yawgmoth", count: 4 },
    ],
  },
  {
    key: "elfen-stamm",
    labelDe: "Elfen-Stamm", labelEn: "Elf Tribal",
    colors: ["G"], colorHex: "#16a34a", icon: "leaf-outline",
    tagsDe: ["Stamm", "Kombo", "Grün"], tagsEn: ["Tribal", "Combo", "Green"],
    summaryDe: "Elfen produzieren Mana und erschaffen Horden. Ziel: so viele Elfen wie möglich aufbauen, dann 'Craterhoof Behemoth' spielen und mit einem Schlag gewinnen.",
    summaryEn: "Elves produce mana and build hordes. Goal: assemble as many elves as possible, then play 'Craterhoof Behemoth' and win in one swing.",
    whyDe: "'Elvish Archdruid' ist der Schlüssel: er produziert Mana für jeden Elfen. Mit 5 Elfen im Spiel hat man 5+ Mana — genug für 'Craterhoof Behemoth', der alle Kreaturen zu Riesenmonstern macht. 'Heritage Druid' ermöglicht das Ausspielen des gesamten Decks in einer Runde. 'Chord of Calling' findet den Craterhoof genau wenn man ihn braucht.",
    whyEn: "'Elvish Archdruid' is the key: it produces mana for each elf. With 5 elves in play you have 5+ mana — enough for 'Craterhoof Behemoth', which turns all creatures into giants. 'Heritage Druid' enables playing the entire deck in one turn. 'Chord of Calling' finds the Craterhoof exactly when needed.",
    slots: [
      { name: "Llanowar Elves",               count: 4, roleDe: "1-Mana-Rampe: Elfen-Mana-Basis",                         roleEn: "1-mana ramp: elf mana base" },
      { name: "Elvish Mystic",                count: 4, roleDe: "Zweiter Satz 1-Mana-Rampe-Elfen",                         roleEn: "Second set of 1-mana ramp elves" },
      { name: "Heritage Druid",               count: 4, roleDe: "Kern-Kombo: Mana aus getappten Elfen",                   roleEn: "Core combo: mana from tapped elves" },
      { name: "Elvish Archdruid",             count: 4, roleDe: "Lord + Mana-Generator: Herzstück des Decks",             roleEn: "Lord + mana generator: heart of the deck" },
      { name: "Dwynen's Elite",               count: 4, roleDe: "Schafft Token: verdoppelt Elfenzahl schnell",             roleEn: "Creates token: quickly doubles elf count" },
      { name: "Collected Company",            count: 4, roleDe: "Findet 2 Kreaturen sofort: Schlüssel-Beschleuniger",     roleEn: "Finds 2 creatures instantly: key accelerator" },
      { name: "Chord of Calling",             count: 4, roleDe: "Sucht Craterhoof oder anderen Schlüsselelfen",           roleEn: "Finds Craterhoof or other key elves" },
      { name: "Ezuri, Renegade Leader",       count: 3, roleDe: "Schlüssel-Lord: pumpt alle Elfen für Massenangriff",     roleEn: "Key lord: pumps all elves for alpha strike" },
      { name: "Craterhoof Behemoth",          count: 2, roleDe: "Gewinn-Bedingung: alle Kreaturen werden Riesen",         roleEn: "Win condition: all creatures become giants" },
      { name: "Regal Force",                  count: 1, roleDe: "Karten-Zieher: zieht für jeden grünen Kreatur",          roleEn: "Card draw: draws for each green creature" },
    ],
    lands: [
      { name: "Nykthos, Shrine to Nyx", count: 4 },
      { name: "Forest", count: 18 },
    ],
  },
  {
    key: "goblin-stamm",
    labelDe: "Goblin-Stamm", labelEn: "Goblin Tribal",
    colors: ["R"], colorHex: "#e67e22", icon: "bug-outline",
    tagsDe: ["Stamm", "Aggro", "Rot"], tagsEn: ["Tribal", "Aggro", "Red"],
    summaryDe: "Horden von kleinen Goblins überwältigen den Gegner durch schiere Anzahl und Hast. Goblin-Lords lassen die ganze Horde gleichzeitig angreifen.",
    summaryEn: "Hordes of small goblins overwhelm the opponent through sheer numbers and haste. Goblin lords let the entire horde attack simultaneously.",
    whyDe: "'Goblin Lackey' ist die gefährlichste 1-Mana-Kreatur im Deck: wenn sie Schaden macht, kann man kostenlos einen Goblin ausspielen — selbst einen 5-6-Mana-Goblin. 'Goblin Warchief' gibt allen Goblins Hast und macht sie günstiger. 'Krenko' erstellt jede Runde so viele Token wie Goblins im Spiel sind — er verdoppelt die Horde jede Runde!",
    whyEn: "'Goblin Lackey' is the most dangerous 1-mana creature: when it deals damage, you can play any goblin for free — even a 5-6 mana goblin. 'Goblin Warchief' gives all goblins haste and makes them cheaper. 'Krenko' creates tokens equal to the number of goblins each turn — doubling the horde every round!",
    slots: [
      { name: "Goblin Lackey",                count: 4, roleDe: "Kern-Droher: spielt kostenlose Goblins bei Schaden",      roleEn: "Core threat: plays free goblins when it deals damage" },
      { name: "Mogg Fanatic",                 count: 4, roleDe: "1-Mana-Brandquelle + Blocker-Entfernung",                 roleEn: "1-mana burn source + blocker removal" },
      { name: "Goblin Piledriver",            count: 4, roleDe: "Wird riesig: +2/+0 für jeden anderen Goblin beim Angriff", roleEn: "Gets huge: +2/+0 per other attacking goblin" },
      { name: "Goblin Warchief",              count: 4, roleDe: "Hast + günstiger für alle Goblins",                       roleEn: "Haste + cheaper for all goblins" },
      { name: "Goblin Chieftain",             count: 4, roleDe: "Lord: +2/+1 + Hast für alle Goblins",                    roleEn: "Lord: +2/+1 + haste for all goblins" },
      { name: "Krenko, Mob Boss",             count: 4, roleDe: "Verdoppelt die Goblin-Horde jede Runde",                  roleEn: "Doubles the goblin horde each turn" },
      { name: "Goblin Ringleader",            count: 4, roleDe: "Kartenvorteil: findet bis zu 4 Goblins",                 roleEn: "Card advantage: finds up to 4 goblins" },
      { name: "Lightning Bolt",               count: 4, roleDe: "Entfernung + Brand für Direktschaden",                    roleEn: "Removal + burn for direct damage" },
    ],
    lands: [
      { name: "Cavern of Souls", count: 4 },
      { name: "Mountain", count: 20 },
    ],
  },
  {
    key: "vampir-stamm",
    labelDe: "Vampir-Stamm", labelEn: "Vampire Tribal",
    colors: ["B", "R"], colorHex: "#d3202a", icon: "moon-outline",
    tagsDe: ["Stamm", "Mittel", "Schwarz/Rot"], tagsEn: ["Tribal", "Intermediate", "Black/Red"],
    summaryDe: "Vampir-Decks kombinieren Aggression mit Lebenspunkte-Gewinn. Die Lords stärken die ganze Horde während Vampir-Fähigkeiten wie Blutsaugen für Dauerhaftigkeit sorgen.",
    summaryEn: "Vampire decks combine aggression with life gain. Lords strengthen the entire horde while vampire abilities like lifelink ensure sustainability.",
    whyDe: "'Champion of Dusk' ist der Dreh- und Angelpunkt: er zieht Karten gleich der Vampir-Anzahl beim Betreten — bei 4 Vampiren zieht man 4 Karten sofort. 'Vampire Nocturnus' ist ein Lord der alle Vampire fliegend und +2/+1 macht wenn die oberste Karte schwarz ist — bei Mono-Black fast immer aktiv.",
    whyEn: "'Champion of Dusk' is the centerpiece: it draws cards equal to vampire count on ETB — with 4 vampires you draw 4 cards immediately. 'Vampire Nocturnus' is a lord that gives all vampires flying and +2/+1 when the top card is black — almost always active in Mono-Black.",
    slots: [
      { name: "Legion's Landing",             count: 4, roleDe: "Eröffnungszug: 1/1-Vampir + Mana-Quelle",                roleEn: "Opening play: 1/1 vampire + mana source" },
      { name: "Viscera Seer",                 count: 4, roleDe: "Opfer-Outlet + Skrying für Bibliotheks-Kontrolle",       roleEn: "Sacrifice outlet + scry for library control" },
      { name: "Gifted Aetherborn",            count: 4, roleDe: "2/3 Todesberührung + Lebenspunkte-Gewinn",               roleEn: "2/3 deathtouch + lifelink" },
      { name: "Champion of Dusk",             count: 4, roleDe: "Mächtiger Kartenzieher: zieht 1 pro Vampir",             roleEn: "Powerful card draw: draws 1 per vampire" },
      { name: "Vampire Nocturnus",            count: 4, roleDe: "Lord: Fliegen + +2/+1 wenn top Karte schwarz",           roleEn: "Lord: flying + +2/+1 when top card is black" },
      { name: "Indulgent Aristocrat",         count: 4, roleDe: "1-Mana-Vampir + Opfer-Verstärker",                       roleEn: "1-mana vampire + sacrifice enhancer" },
      { name: "Kalitas, Traitor of Ghet",     count: 3, roleDe: "Friedhof-Hate + Token-Generator",                       roleEn: "Graveyard hate + token generator" },
      { name: "Fatal Push",                   count: 4, roleDe: "Beste Schwarze Einzelentfernung",                        roleEn: "Best black single removal" },
      { name: "Sorin, Imperious Bloodlord",   count: 3, roleDe: "Planeswalker: verstärkt Vampir-Strategie komplett",      roleEn: "Planeswalker: enhances entire vampire strategy" },
    ],
    lands: [
      { name: "Swamp", count: 20 },
      { name: "Blood Crypt", count: 4 },
    ],
  },
  {
    key: "token-strategie",
    labelDe: "Token-Strategie", labelEn: "Token Strategy",
    colors: ["W", "G"], colorHex: "#f59e0b", icon: "copy-outline",
    tagsDe: ["Midrange", "Mittel", "Weiß/Grün"], tagsEn: ["Midrange", "Intermediate", "White/Green"],
    summaryDe: "Erschaffe eine Armee kleiner Token-Kreaturen, stärke sie mit Verstärkern und überrenne den Gegner mit einem massiven Angriff.",
    summaryEn: "Create an army of small token creatures, strengthen them with enhancers, then overwhelm the opponent with a massive attack.",
    whyDe: "'Intangible Virtue' ist der Grundpfeiler: gibt allen Token +1/+1 und Vigilanz für 2 Mana. 'Lingering Souls' schafft 4 Token (2 sofort, 2 im nächsten Zug) für nur 2 Mana. 'Nissa, Voice of Zendikar' macht jede Runde einen 0/1-Pflanzentoken und kann alle Kreaturen mit Zählern verstärken. 'Craterhoof Behemoth' am Ende verwandelt 10-15 Token in eine unaufhaltbare Welle.",
    whyEn: "'Intangible Virtue' is the cornerstone: gives all tokens +1/+1 and vigilance for 2 mana. 'Lingering Souls' creates 4 tokens (2 now, 2 next turn) for just 2 mana. 'Nissa, Voice of Zendikar' makes a 0/1 plant token each turn. 'Craterhoof Behemoth' turns 10-15 tokens into an unstoppable wave.",
    slots: [
      { name: "Llanowar Elves",               count: 4, roleDe: "Rampe: kommt man früher zu den starken Karten",          roleEn: "Ramp: helps cast stronger cards earlier" },
      { name: "Intangible Virtue",            count: 4, roleDe: "Verstärker: alle Token +1/+1 + Vigilanz",                roleEn: "Enhancer: all tokens +1/+1 + vigilance" },
      { name: "Lingering Souls",              count: 4, roleDe: "Bester Token-Generator: 4 fliegende Spirit-Token",       roleEn: "Best token generator: 4 flying spirit tokens" },
      { name: "Raise the Alarm",              count: 4, roleDe: "2 Soldaten-Token instant als Blocker oder Angreifer",    roleEn: "2 soldier tokens instant as blocker or attacker" },
      { name: "Midnight Haunting",            count: 4, roleDe: "2 fliegende Geist-Token am Ende des Gegner-Zuges",       roleEn: "2 flying spirit tokens at end of opponent's turn" },
      { name: "Elspeth, Sun's Champion",      count: 3, roleDe: "Macht 3 Token/Zug + Massenentfernung großer Kreaturen",  roleEn: "Makes 3 tokens/turn + mass removal of large creatures" },
      { name: "Nissa, Voice of Zendikar",     count: 3, roleDe: "Token-Maschine + verstärkt alle Kreaturen",             roleEn: "Token machine + buffs all creatures" },
      { name: "Path to Exile",                count: 4, roleDe: "Entfernung: räumt Blocker aus dem Weg",                  roleEn: "Removal: clears blockers" },
      { name: "Craterhoof Behemoth",          count: 2, roleDe: "Gewinn-Bedingung: verwandelt Token in Riesen",           roleEn: "Win condition: turns tokens into giants" },
    ],
    lands: [
      { name: "Temple Garden", count: 4 },
      { name: "Plains", count: 10 },
      { name: "Forest", count: 10 },
    ],
  },
  {
    key: "friedhof-strategie",
    labelDe: "Friedhof-Strategie", labelEn: "Reanimator / Graveyard",
    colors: ["B", "G"], colorHex: "#718096", icon: "cloudy-night-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Schwarz/Grün"], tagsEn: ["Combo", "Advanced", "Black/Green"],
    summaryDe: "Fülle deinen Friedhof mit mächtigen Kreaturen und bringe sie dann für viel weniger als ihre Manakosten zurück ins Spiel.",
    summaryEn: "Fill your graveyard with powerful creatures then return them to play for far less than their mana cost.",
    whyDe: "Reanimator ist eine der ältesten Kombo-Strategien: Man legt eine 8-Mana-Kreatur wie 'Griselbrand' in Runde 1-2 in den Friedhof (per 'Faithless Looting' oder 'Entomb') und bringt sie dann mit 'Reanimate' für 1 Mana zurück. Das Ergebnis: ein 7/7-Monster mit Flug und Lebenspunkte-Gewinn in Runde 2.",
    whyEn: "Reanimator is one of the oldest combo strategies: put an 8-mana creature like 'Griselbrand' into the graveyard on turn 1-2 then return it with 'Reanimate' for 1 mana. Result: a 7/7 flying lifelink monster on turn 2.",
    slots: [
      { name: "Entomb",                        count: 4, roleDe: "Legt jede Kreatur in den Friedhof für 1 Mana",           roleEn: "Puts any creature into graveyard for 1 mana" },
      { name: "Faithless Looting",             count: 4, roleDe: "Karten ablegen + ziehen: füllt Friedhof schnell",        roleEn: "Discard + draw: fills graveyard quickly" },
      { name: "Reanimate",                     count: 4, roleDe: "Kern-Beschwörer: bringt alles für 1 Mana zurück",        roleEn: "Core reanimator: returns anything for 1 mana" },
      { name: "Animate Dead",                  count: 4, roleDe: "Zweiter Satz Beschwörungs-Karten",                       roleEn: "Second set of reanimation spells" },
      { name: "Griselbrand",                   count: 4, roleDe: "Beste Ziel: 7/7 Fliegen + zieht 7 Karten",              roleEn: "Best target: 7/7 flying + draw 7 cards" },
      { name: "Iona, Shield of Emeria",        count: 2, roleDe: "Sperrt komplette Farbe des Gegners",                     roleEn: "Locks out opponent's entire color" },
      { name: "Grave Titan",                   count: 2, roleDe: "6/6 der 2 Zombie-Token erstellt + bei Angriff",         roleEn: "6/6 that creates 2 zombie tokens on ETB + attack" },
      { name: "Thoughtseize",                  count: 4, roleDe: "Handstörer: entfernt Gegenmittel",                      roleEn: "Hand disruption: removes answers" },
      { name: "Ponder",                        count: 4, roleDe: "Karten-Suche: findet die richtigen Teile früh",          roleEn: "Card search: finds the right pieces early" },
    ],
    lands: [
      { name: "Verdant Catacombs", count: 4 },
      { name: "Swamp", count: 16 },
      { name: "Forest", count: 4 },
    ],
  },
  {
    key: "opfer-strategie",
    labelDe: "Opfer-Strategie (Aristokraten)", labelEn: "Sacrifice Strategy (Aristocrats)",
    colors: ["B", "R", "W"], colorHex: "#d3202a", icon: "flash-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Mehrfarbig"], tagsEn: ["Combo", "Advanced", "Multi-color"],
    summaryDe: "Opfere deine eigenen Kreaturen immer wieder für Mana und Effekte. Jeder Tod ist ein Gewinn wenn genug Sterbe-Trigger aktiv sind.",
    summaryEn: "Sacrifice your own creatures repeatedly for mana and effects. Every death is a gain when enough death triggers are active.",
    whyDe: "Aristokraten-Decks spielen eine Endlos-Schleife: 'Gravecrawler' + 'Phyrexian Altar' + ein Zombie = unendliche Mana und Sterbe-Trigger. 'Zulaport Cutthroat' oder 'Blood Artist' schaden dem Gegner für jeden Sterbefall.",
    whyEn: "Aristocrat decks play an infinite loop: 'Gravecrawler' + 'Phyrexian Altar' + a zombie = infinite mana and death triggers. 'Zulaport Cutthroat' or 'Blood Artist' damages the opponent for each death.",
    slots: [
      { name: "Gravecrawler",                 count: 4, roleDe: "Kern-Schleife: kommt immer aus Friedhof zurück",         roleEn: "Core loop piece: always returns from graveyard" },
      { name: "Blood Artist",                  count: 4, roleDe: "Schadet Gegner 1 bei jedem Sterbefall",                  roleEn: "Damages opponent 1 for each death" },
      { name: "Zulaport Cutthroat",            count: 4, roleDe: "Zweiter Satz Sterbe-Schaden",                            roleEn: "Second set of death damage triggers" },
      { name: "Viscera Seer",                  count: 4, roleDe: "Kostenloses Opfer-Outlet + Skrying",                     roleEn: "Free sacrifice outlet + scry" },
      { name: "Cartel Aristocrat",             count: 4, roleDe: "Schutz-Outlet: opfert für Unzerstörbarkeits-Schutz",    roleEn: "Protection outlet: sacrifices for indestructible shield" },
      { name: "Lingering Souls",               count: 4, roleDe: "Token-Masse als Opfer-Futter",                          roleEn: "Token mass as sacrifice fodder" },
      { name: "Young Wolf",                    count: 4, roleDe: "Unsterblich: stirbt zweimal = 2x Sterbe-Trigger",        roleEn: "Undying: dies twice = 2x death triggers" },
      { name: "Murderous Rider",               count: 4, roleDe: "Entfernung + selbst als Kreatur danach",                 roleEn: "Removal + becomes a creature afterward" },
    ],
    lands: [
      { name: "Godless Shrine", count: 4 },
      { name: "Blood Crypt", count: 4 },
      { name: "Swamp", count: 16 },
    ],
  },
  {
    key: "zaehler-strategie",
    labelDe: "+1/+1 Zähler-Strategie", labelEn: "+1/+1 Counter Strategy",
    colors: ["G", "B"], colorHex: "#16a34a", icon: "trending-up-outline",
    tagsDe: ["Midrange", "Mittel", "Grün/Schwarz"], tagsEn: ["Midrange", "Intermediate", "Green/Black"],
    summaryDe: "Verteile +1/+1-Zähler auf Kreaturen und nutze Proliferate um sie zu multiplizieren. Kleine Kreaturen wachsen zu unaufhaltbaren Monstern.",
    summaryEn: "Distribute +1/+1 counters on creatures and use Proliferate to multiply them. Small creatures grow into unstoppable monsters.",
    whyDe: "Proliferate ist die Schlüsselfähigkeit: sie verdoppelt alle Zähler auf allen Permanenten. 'Ozolith' sammelt alle Zähler wenn eine Kreatur stirbt. 'Winding Constrictor' verdoppelt alle Zähler-Platzierungen — das ist exponentielles Wachstum.",
    whyEn: "Proliferate is the key ability: it adds one more of each counter on each permanent. 'Ozolith' collects all counters when a creature dies. 'Winding Constrictor' doubles all counter placements — that's exponential growth.",
    slots: [
      { name: "Winding Constrictor",           count: 4, roleDe: "Kern: verdoppelt alle Zähler-Platzierungen",            roleEn: "Core: doubles all counter placements" },
      { name: "Hardened Scales",               count: 4, roleDe: "Verstärker: +1 extra Zähler bei jeder Platzierung",     roleEn: "Enhancer: +1 extra counter on each placement" },
      { name: "Pelt Collector",                count: 4, roleDe: "Früher Zähler-Sammler der schnell wächst",              roleEn: "Early counter collector that grows fast" },
      { name: "Servant of the Scale",          count: 4, roleDe: "Überträgt Zähler an andere Kreatur beim Sterben",       roleEn: "Transfers counters to another creature on death" },
      { name: "Ozolith",                       count: 4, roleDe: "Zähler-Speicher: rettet Zähler vom Tod",                roleEn: "Counter storage: saves counters from death" },
      { name: "Hydroid Krasis",                count: 4, roleDe: "Flexibler Zähler-Träger + Karten-Zieher",              roleEn: "Flexible counter carrier + card draw" },
      { name: "Rishkar, Peema Renegade",        count: 4, roleDe: "Legt Zähler + Kreaturen mit Zählern produzieren Mana", roleEn: "Adds counters + creatures with counters tap for mana" },
      { name: "Ezuri, Claw of Progress",       count: 2, roleDe: "Sammelt Erfahrungs-Zähler + verstärkt Kreatur massiv", roleEn: "Gains experience counters + massively buffs creature" },
      { name: "Evolution Sage",                count: 4, roleDe: "Proliferate bei jedem Land-Ausspielen",                 roleEn: "Proliferate every time you play a land" },
    ],
    lands: [
      { name: "Overgrown Tomb", count: 4 },
      { name: "Forest", count: 14 },
      { name: "Swamp", count: 6 },
    ],
  },
];

// ─── Standard Archetypes ───────────────────────────────────────────────────

const STANDARD_ARCHETYPES: Archetype[] = [
  {
    key: "std-roter-aggro", format: "standard", deckSize: 60,
    labelDe: "Rotes Aggro (Standard)", labelEn: "Red Aggro (Standard)",
    colors: ["R"], colorHex: "#e67e22", icon: "flame-outline",
    tagsDe: ["Aggro", "Einfach", "Rot"], tagsEn: ["Aggro", "Beginner", "Red"],
    summaryDe: "Das schnellste Standard-Deck. Mit Prowess-Kreaturen und günstigen Brand-Sprüchen gewinnt man oft vor Runde 5.",
    summaryEn: "The fastest Standard deck. With Prowess creatures and cheap burn spells, games are often won before turn 5.",
    whyDe: "'Slickshot Show-Off' und 'Heartfire Hero' sind die Kernkarten: sie wachsen mit jedem Spruch. 'Play with Fire' und 'Lightning Strike' sorgen für Direktschaden und Kreaturen-Entfernung gleichzeitig.",
    whyEn: "'Slickshot Show-Off' and 'Heartfire Hero' are the core cards: they grow with each spell. 'Play with Fire' and 'Lightning Strike' deal direct damage and remove creatures simultaneously.",
    slots: [
      { name: "Slickshot Show-Off",     count: 4, roleDe: "Kern-Droher: Prowess + fliegen",               roleEn: "Core threat: Prowess + flying" },
      { name: "Heartfire Hero",         count: 4, roleDe: "Wächst mit Zaubersprüchen + Direktschaden",    roleEn: "Grows with spells + direct damage" },
      { name: "Monastery Swiftspear",   count: 4, roleDe: "1-Mana Hast + Prowess",                        roleEn: "1-mana haste + Prowess" },
      { name: "Screaming Nemesis",      count: 3, roleDe: "Zähes Ziel: kehrt als Token zurück",           roleEn: "Resilient threat: returns as token" },
      { name: "Play with Fire",         count: 4, roleDe: "1-Mana-Brand + Scrying",                       roleEn: "1-mana burn + scry" },
      { name: "Lightning Strike",       count: 4, roleDe: "Vielseitige Entfernung + Brand",               roleEn: "Versatile removal + burn" },
      { name: "Monstrous Rage",         count: 4, roleDe: "Sofortige Trampel + Stärkung für 1 Mana",      roleEn: "Instant trample + buff for 1 mana" },
      { name: "Emberheart Challenger",  count: 4, roleDe: "Trampel + Opfer für Brand-Synergien",          roleEn: "Trample + sacrifice for burn synergies" },
      { name: "Urabrask's Forge",       count: 3, roleDe: "Dauerhafte Token-Fabrik jeden Zug",            roleEn: "Persistent token factory each turn" },
    ],
    lands: [{ name: "Mountain", count: 20 }],
  },
  {
    key: "std-weiss-weenie", format: "standard", deckSize: 60,
    labelDe: "Weißer Aufmarsch (Standard)", labelEn: "White Weenie (Standard)",
    colors: ["W"], colorHex: "#f8d878", icon: "shield-checkmark-outline",
    tagsDe: ["Aggro", "Einfach", "Weiß"], tagsEn: ["Aggro", "Beginner", "White"],
    summaryDe: "Günstige weiße Kreaturen mit Synergie-Boni überrennen den Gegner. Soldier-Synergien und Vigilanz machen das Deck defensiv und offensiv gleichzeitig.",
    summaryEn: "Cheap white creatures with synergy bonuses overwhelm the opponent. Soldier synergies and vigilance make the deck both offensive and defensive.",
    whyDe: "'Resolute Reinforcements' und 'Knight-Errant of Eos' erzeugen kostenlos Tokens und Kreaturen. 'Warden of the Inner Sky' wächst mit jedem Angriff.",
    whyEn: "'Resolute Reinforcements' and 'Knight-Errant of Eos' generate free tokens and creatures. 'Warden of the Inner Sky' grows with each attack.",
    slots: [
      { name: "Hopeful Initiate",        count: 4, roleDe: "1-Mana-Zähler-Engine + Enchantment-Entfernung", roleEn: "1-mana counter engine + enchantment removal" },
      { name: "Warden of the Inner Sky", count: 4, roleDe: "Wächst mit Angriffen, Flugfähigkeit erspielbar", roleEn: "Grows with attacks, can gain flying" },
      { name: "Resolute Reinforcements", count: 4, roleDe: "Sofort-Verstärkung + 2 Kreaturen für 2 Mana",    roleEn: "Flash 2 creatures for 2 mana" },
      { name: "Knight-Errant of Eos",    count: 4, roleDe: "Schafft 2 Soldaten + 3/3 Körper",               roleEn: "Creates 2 soldiers + 3/3 body" },
      { name: "Recruitment Officer",     count: 4, roleDe: "Karten-Zieher: findet 1-Mana-Kreaturen",         roleEn: "Card draw: finds 1-mana creatures" },
      { name: "Luminarch Aspirant",      count: 4, roleDe: "Zähler-Motor: stärkt jeden Zug eine Kreatur",    roleEn: "Counter engine: buffs a creature every turn" },
      { name: "Brave the Elements",      count: 3, roleDe: "Schutz + Durchbruch für alle weißen Kreaturen",  roleEn: "Protection + evasion for all white creatures" },
      { name: "Brutal Cathar",           count: 4, roleDe: "Entfernung als Kreatur + Mondstamm-Synergie",    roleEn: "Removal on a creature + daybound synergy" },
      { name: "Thalia, Guardian of Thraben", count: 3, roleDe: "Störer: Sprüche des Gegners kosten mehr",    roleEn: "Disruptor: opponent's spells cost more" },
    ],
    lands: [{ name: "Plains", count: 20 }],
  },
  {
    key: "std-dimir-kontrolle", format: "standard", deckSize: 60,
    labelDe: "Dimir Kontrolle (Standard)", labelEn: "Dimir Control (Standard)",
    colors: ["U", "B"], colorHex: "#0e68ab", icon: "water-outline",
    tagsDe: ["Kontrolle", "Fortgeschritten", "Blau/Schwarz"], tagsEn: ["Control", "Advanced", "Blue/Black"],
    summaryDe: "Kontrolliere das Spiel mit Gegenzaubern und Entfernung, dann gewinne mit mächtigen Kreaturen. Enduring Curiosity und Faerie-Synergien dominieren das Mittelspiel.",
    summaryEn: "Control the game with counterspells and removal, then win with powerful threats. Enduring Curiosity and Faerie synergies dominate the mid-game.",
    whyDe: "'Enduring Curiosity' ist das Herzstück: es zieht Karten wenn Kreaturen Schaden machen oder sterben. 'No More Lies' ist Gegenzauber + Scrying für 2 Mana.",
    whyEn: "'Enduring Curiosity' is the centerpiece: it draws cards when creatures deal damage or die. 'No More Lies' is counterspell + scry for 2 mana.",
    slots: [
      { name: "Deep-Cavern Bat",     count: 4, roleDe: "1-Mana Handstörer + Flugbedrohung",          roleEn: "1-mana hand disruptor + flying threat" },
      { name: "Faerie Mastermind",   count: 4, roleDe: "Sofort-Faerie + Kartenvorteil-Schleife",      roleEn: "Flash faerie + card advantage loop" },
      { name: "Enduring Curiosity",  count: 4, roleDe: "Enchantment: Karten ziehen für Kreaturen",    roleEn: "Enchantment: draw cards for creatures" },
      { name: "Psychic Frog",        count: 4, roleDe: "Wächst durch Abwerfen, schwer zu stoppen",    roleEn: "Grows through discarding, hard to block" },
      { name: "No More Lies",        count: 4, roleDe: "2-Mana Gegenzauber + Scrying",                roleEn: "2-mana counterspell + scry" },
      { name: "Cut Down",            count: 4, roleDe: "1-Mana Entfernung für kleine Kreaturen",      roleEn: "1-mana removal for small creatures" },
      { name: "Preacher of the Schism", count: 3, roleDe: "Karten-Motor + Zombie-Token",              roleEn: "Card engine + zombie tokens" },
      { name: "Atraxa, Grand Unifier", count: 3, roleDe: "Gewinn-Bedingung: zieht 4 Karten beim Beschwören", roleEn: "Win condition: draws 4 cards on ETB" },
      { name: "Sunken Palace",       count: 2, roleDe: "Doppel-Land: Island + Swamp",                 roleEn: "Dual land: Island + Swamp" },
    ],
    lands: [
      { name: "Island", count: 10 },
      { name: "Swamp", count: 10 },
      { name: "Undercity Sewers", count: 4 },
    ],
  },
  {
    key: "std-gruul-lands", format: "standard", deckSize: 60,
    labelDe: "Gruul Landsfall (Standard)", labelEn: "Gruul Landfall (Standard)",
    colors: ["R", "G"], colorHex: "#16a34a", icon: "earth-outline",
    tagsDe: ["Midrange", "Mittel", "Rot/Grün"], tagsEn: ["Midrange", "Intermediate", "Red/Green"],
    summaryDe: "Spiele Länder für Landfall-Trigger. Jedes Land erschafft Kreaturen, gibt Zähler oder verursacht Schaden. Mit Rampe mehrmals pro Zug auslösbar.",
    summaryEn: "Play lands to trigger Landfall. Every land creates creatures, adds counters, or deals damage. With ramp, multiple triggers per turn are possible.",
    whyDe: "'Roaring Earth' gibt +1/+1-Zähler auf Kreaturen bei Landfall. 'Pia Nalaar' und 'Fearless Liberator' sorgen für aggressiven Druck.",
    whyEn: "'Roaring Earth' puts +1/+1 counters on creatures each Landfall. 'Pia Nalaar' and 'Fearless Liberator' provide aggressive pressure.",
    slots: [
      { name: "Roaring Earth",          count: 4, roleDe: "Landfall: +1/+1 Zähler auf Kreatur",         roleEn: "Landfall: +1/+1 counter on creature" },
      { name: "Fearless Liberator",      count: 4, roleDe: "Rampe + aggressiver Angreifer",               roleEn: "Ramp + aggressive attacker" },
      { name: "Outcaster Greenblade",    count: 4, roleDe: "Rampe: legt Land aus Bibliothek",             roleEn: "Ramp: puts land from library" },
      { name: "Pia Nalaar, Consul of Revival", count: 3, roleDe: "Thopter-Fabrik + Opfer-Synergie",     roleEn: "Thopter factory + sacrifice synergy" },
      { name: "Etali, Primal Conqueror", count: 2, roleDe: "Gewinn-Bedingung: spielt Gegner-Karten",     roleEn: "Win condition: plays opponent's cards" },
      { name: "Geological Appraiser",    count: 4, roleDe: "Discover: findet günstige Karten",           roleEn: "Discover: finds cheap cards" },
      { name: "Trumpeting Carnosaur",    count: 3, roleDe: "Discover 5 + riesiger Körper",               roleEn: "Discover 5 + huge body" },
      { name: "Palani's Hatcher",        count: 4, roleDe: "Token-Fabrik + Dinosaurier-Synergie",        roleEn: "Token factory + dinosaur synergy" },
      { name: "Huatli, Poet of Unity",   count: 2, roleDe: "Planeswalker: Dinosaurier + Kartenvorteil", roleEn: "Planeswalker: dinosaurs + card advantage" },
    ],
    lands: [
      { name: "Copperline Gorge", count: 4 },
      { name: "Mountain", count: 8 },
      { name: "Forest", count: 12 },
    ],
  },
  {
    key: "std-golgari-midrange", format: "standard", deckSize: 60,
    labelDe: "Golgari Midrange (Standard)", labelEn: "Golgari Midrange (Standard)",
    colors: ["B", "G"], colorHex: "#718096", icon: "skull-outline",
    tagsDe: ["Midrange", "Mittel", "Schwarz/Grün"], tagsEn: ["Midrange", "Intermediate", "Black/Green"],
    summaryDe: "Resiliente Kreaturen, starke Entfernung und Kartenvorteil. Golgari-Midrange überlebt Aggro durch Blocken und Kontrolle durch Droher.",
    summaryEn: "Resilient creatures, strong removal, and card advantage. Golgari Midrange survives aggro through blocking and control through threats.",
    whyDe: "'Mosswood Dreadknight' ist die stärkste 2-Mana-Kreatur: er kehrt aus dem Friedhof zurück. 'Restless Cottage' ist eine Kreatur die auch Land ist.",
    whyEn: "'Mosswood Dreadknight' is the strongest 2-mana creature: it returns from the graveyard. 'Restless Cottage' is a creature that's also a land.",
    slots: [
      { name: "Mosswood Dreadknight",  count: 4, roleDe: "2-Mana-Droher: kehrt immer zurück",          roleEn: "2-mana threat: always returns" },
      { name: "Caustic Bronco",        count: 4, roleDe: "Rampe + Kartenvorteil: wirft ab für Mana",   roleEn: "Ramp + card advantage: discards for mana" },
      { name: "Glissa Sunslayer",      count: 3, roleDe: "Zähes Wesen + Entfernung + Karten ziehen",   roleEn: "Resilient creature + removal + card draw" },
      { name: "Sheoldred, the Apocalypse", count: 3, roleDe: "Lebensgewinn für ziehen, Schaden für Gegner", roleEn: "Life gain for drawing, damage for opponent" },
      { name: "Obliterating Bolt",     count: 4, roleDe: "Entfernt und exiliert Kreaturen/Planeswalker", roleEn: "Removes and exiles creatures/planeswalkers" },
      { name: "Go for the Throat",     count: 4, roleDe: "2-Mana: zerstört Nicht-Artefakt-Kreaturen",  roleEn: "2-mana: destroys non-artifact creatures" },
      { name: "Titania's Command",     count: 3, roleDe: "Mehrzweck: Länder/Zähler/Token/Zombie",      roleEn: "Multi-mode: lands/counters/tokens/zombies" },
      { name: "Graveyard Trespasser", count: 4, roleDe: "Friedhof-Hate + schwer zu entfernen",        roleEn: "Graveyard hate + hard to remove" },
    ],
    lands: [
      { name: "Overgrown Tomb", count: 4 },
      { name: "Forest", count: 10 },
      { name: "Swamp", count: 10 },
    ],
  },
];

// ─── Commander Archetypes ──────────────────────────────────────────────────

const COMMANDER_ARCHETYPES: Archetype[] = [
  {
    key: "cmd-purphoros", format: "commander", deckSize: 100,
    commanderSlot: { name: "Purphoros, God of the Forge", count: 1, roleDe: "Commander: 2 Schaden wenn Kreatur beschworen wird", roleEn: "Commander: 2 damage when creature enters" },
    labelDe: "Purphoros Token-Schaden", labelEn: "Purphoros Token Damage",
    colors: ["R"], colorHex: "#e67e22", icon: "flame-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Rot"], tagsEn: ["Combo", "Advanced", "Red"],
    summaryDe: "Purphoros verursacht 2 Schaden an alle Gegner wenn eine Kreatur das Schlachtfeld betritt. Mit Massen-Token-Erzeugung tötet man alle 3-4 Gegner gleichzeitig.",
    summaryEn: "Purphoros deals 2 damage to all opponents when any creature enters the battlefield. With mass token generation, all 3-4 opponents die simultaneously.",
    whyDe: "In Commander hat jeder Spieler 40 Leben — aber Purphoros schadet ALLEN Gegnern gleichzeitig. 'Krenko' verdoppelt die Goblin-Horde jede Runde. Mit 20 Token erschafft Purphoros 40 Schaden insgesamt — genug um 3 Spieler zu töten.",
    whyEn: "In Commander each player has 40 life — but Purphoros damages ALL opponents simultaneously. 'Krenko' doubles the goblin horde each turn. With 20 tokens, Purphoros creates 40 total damage — enough to kill 3 players.",
    slots: [
      { name: "Krenko, Mob Boss",        count: 1, roleDe: "Verdoppelt Goblins jede Runde",              roleEn: "Doubles goblins each turn" },
      { name: "Tempt with Vengeance",    count: 1, roleDe: "Erschafft X Token sofort",                   roleEn: "Creates X tokens immediately" },
      { name: "Dragon Fodder",           count: 1, roleDe: "2 Token für 2 Mana",                         roleEn: "2 tokens for 2 mana" },
      { name: "Hordeling Outburst",      count: 1, roleDe: "3 Token für 3 Mana",                         roleEn: "3 tokens for 3 mana" },
      { name: "Krenko's Command",        count: 1, roleDe: "2 Goblin-Token für 2 Mana",                  roleEn: "2 goblin tokens for 2 mana" },
      { name: "Empty the Warrens",       count: 1, roleDe: "X Goblin-Token für viele Sprüche",           roleEn: "X goblin tokens based on storm count" },
      { name: "Mogg War Marshal",        count: 1, roleDe: "Kommt mit Token und hinterlässt Token",      roleEn: "Enters with token and leaves token" },
      { name: "Siege-Gang Commander",    count: 1, roleDe: "ETB: 3 Goblins + Opfer-Outlet für Brand",   roleEn: "ETB: 3 goblins + sacrifice outlet for burn" },
      { name: "Goblin Rabblemaster",     count: 1, roleDe: "Erschafft Token + Angriff-Erzwingung",       roleEn: "Creates tokens + forces attacks" },
      { name: "Impact Tremors",          count: 1, roleDe: "Zweiter Purphoros-Effekt: 1 Schaden pro ETB", roleEn: "Second Purphoros effect: 1 damage per ETB" },
      { name: "Goblin Bombardment",      count: 1, roleDe: "Kostenloses Opfer-Outlet für Brand",         roleEn: "Free sacrifice outlet for burn" },
      { name: "Warstorm Surge",          count: 1, roleDe: "Kreaturen-ETB: sofort X Schaden machen",     roleEn: "Creature ETB: immediately deal X damage" },
      { name: "Lightning Bolt",          count: 1, roleDe: "3 Schaden für 1 Mana",                       roleEn: "3 damage for 1 mana" },
      { name: "Chaos Warp",              count: 1, roleDe: "Universelle Rote Entfernung",                 roleEn: "Universal red removal" },
      { name: "Sol Ring",                count: 1, roleDe: "Commander-Staple: 2 farbloses Mana",         roleEn: "Commander staple: 2 colorless mana" },
      { name: "Arcane Signet",           count: 1, roleDe: "2 Mana Mana-Stein",                          roleEn: "2-mana mana rock" },
      { name: "Skullclamp",              count: 1, roleDe: "2 Karten ziehen wenn 1/1 stirbt",            roleEn: "Draw 2 cards when a 1/1 dies" },
      { name: "Aggravated Assault",      count: 1, roleDe: "Zusätzliche Kampfphasen für mehr Schaden",   roleEn: "Extra combat phases for more damage" },
    ],
    lands: [
      { name: "Cavern of Souls", count: 1 },
      { name: "Nykthos, Shrine to Nyx", count: 1 },
      { name: "Valakut, the Molten Pinnacle", count: 1 },
      { name: "Mountain", count: 36 },
    ],
  },
  {
    key: "cmd-meren", format: "commander", deckSize: 100,
    commanderSlot: { name: "Meren of Clan Nel Toth", count: 1, roleDe: "Commander: Erfahrungsmarken zum Wiederbeleben von Kreaturen", roleEn: "Commander: experience counters to reanimate creatures" },
    labelDe: "Meren Aristokraten", labelEn: "Meren Aristocrats",
    colors: ["B", "G"], colorHex: "#718096", icon: "skull-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Schwarz/Grün"], tagsEn: ["Combo", "Advanced", "Black/Green"],
    summaryDe: "Meren gibt Erfahrungsmarken wenn Kreaturen sterben. Am Ende des Zugs beschwörst du die mächtigste Kreatur zurück die du dir leisten kannst. Eine Synergie-Maschine.",
    summaryEn: "Meren gives experience counters when creatures die. At end of turn, you reanimate the most powerful creature you can afford. A synergy machine.",
    whyDe: "Das Deck opfert günstige Kreaturen um Sterbe-Trigger auszulösen und Meren-Erfahrungsmarken zu sammeln. Mit 7+ Erfahrungsmarken kommt die mächtigste Kreatur zurück. 'Dictate of Erebos' tötet beim Opfern alle Gegner-Kreaturen.",
    whyEn: "The deck sacrifices cheap creatures to trigger death effects and collect Meren experience counters. With 7+ counters, the most powerful creature returns. 'Dictate of Erebos' kills opponent creatures on each sacrifice.",
    slots: [
      { name: "Blood Artist",           count: 1, roleDe: "Schaden bei jedem Sterbefall",               roleEn: "Damage on each death" },
      { name: "Viscera Seer",           count: 1, roleDe: "Kostenloses Opfer-Outlet",                   roleEn: "Free sacrifice outlet" },
      { name: "Grave Pact",             count: 1, roleDe: "Tötet Gegner-Kreaturen bei Opfern",          roleEn: "Kills opponent creatures on sacrifice" },
      { name: "Dictate of Erebos",      count: 1, roleDe: "Zweiter Grave Pact als Sofort-Zauber",       roleEn: "Second Grave Pact as instant" },
      { name: "Fleshbag Marauder",      count: 1, roleDe: "Alle Spieler opfern eine Kreatur",           roleEn: "All players sacrifice a creature" },
      { name: "Savra, Queen of the Golgari", count: 1, roleDe: "Opfer-Payoff: Leben oder Opfer-Entfernung", roleEn: "Sacrifice payoff: life or mass removal" },
      { name: "Eternal Witness",        count: 1, roleDe: "Karte aus Friedhof zurückholen",             roleEn: "Return any card from graveyard" },
      { name: "Buried Alive",           count: 1, roleDe: "Legt 3 Zielkraten in den Friedhof",         roleEn: "Puts 3 target cards in graveyard" },
      { name: "Reanimate",              count: 1, roleDe: "Beschwöre für 1 Mana jede Friedhof-Kreatur", roleEn: "Reanimate any graveyard creature for 1 mana" },
      { name: "Protean Hulk",           count: 1, roleDe: "Tod-Trigger: sucht Kreaturen bis CMC 6",     roleEn: "Death trigger: finds creatures up to CMC 6" },
      { name: "Mikaeus, the Unhallowed", count: 1, roleDe: "Unsterblich: Kreaturen kehren mit Zähler zurück", roleEn: "Undying: creatures return with counter" },
      { name: "Murderous Rider",        count: 1, roleDe: "Entfernung + Kreatur danach",                roleEn: "Removal + creature afterward" },
      { name: "Phyrexian Arena",        count: 1, roleDe: "Kartenvorteil: zieht jede Runde 1 Karte",    roleEn: "Card advantage: draws 1 extra card each turn" },
      { name: "Sol Ring",               count: 1, roleDe: "Commander-Staple: 2 farbloses Mana",         roleEn: "Commander staple: 2 colorless mana" },
      { name: "Arcane Signet",          count: 1, roleDe: "2 Mana Mana-Stein",                          roleEn: "2-mana mana rock" },
      { name: "Golgari Signet",         count: 1, roleDe: "Golgari-Mana-Stein",                         roleEn: "Golgari mana rock" },
      { name: "Jarad, Golgari Lich Lord", count: 1, roleDe: "Opfert Kreatur für X Schaden an alle",    roleEn: "Sacrifice creature for X damage to all" },
      { name: "Seasons Past",           count: 1, roleDe: "Holt alle Karten aus Friedhof zurück",       roleEn: "Returns all cards from graveyard to hand" },
    ],
    lands: [
      { name: "Command Tower", count: 1 },
      { name: "Overgrown Tomb", count: 1 },
      { name: "Woodland Cemetery", count: 1 },
      { name: "Swamp", count: 18 },
      { name: "Forest", count: 18 },
    ],
  },
  {
    key: "cmd-edgar", format: "commander", deckSize: 100,
    commanderSlot: { name: "Edgar Markov", count: 1, roleDe: "Eminenz-Commander: erschafft Vampir-Token vor dem Beschwören", roleEn: "Eminence commander: creates vampire tokens before casting" },
    labelDe: "Edgar Vampir-Stamm", labelEn: "Edgar Vampire Tribal",
    colors: ["W", "B", "R"], colorHex: "#d3202a", icon: "moon-outline",
    tagsDe: ["Stamm", "Mittel", "Mehrfarbig"], tagsEn: ["Tribal", "Intermediate", "Multi-color"],
    summaryDe: "Edgars Eminenz-Fähigkeit erschafft 1/1-Vampir-Token OHNE ihn zu spielen. Jeder gespielte Vampir erschafft kostenlose Token. Die Horde wächst explosiv.",
    summaryEn: "Edgar's Eminence ability creates 1/1 vampire tokens WITHOUT casting him. Every vampire played creates free tokens. The horde grows explosively.",
    whyDe: "Das Deck ist genial: Edgar muss nie gespielt werden — seine Eminenz-Fähigkeit funktioniert aus der Command Zone. Jeder Vampir = +1 kostenloser Token. 'Sorin' verstärkt alle Vampire, 'Olivia' macht Gegner-Kreaturen zu Vampiren.",
    whyEn: "The deck is brilliant: Edgar never needs to be cast — his Eminence ability works from the Command Zone. Every vampire = +1 free token. 'Sorin' buffs all vampires, 'Olivia' turns opponent creatures into vampires.",
    slots: [
      { name: "Legion's Landing",         count: 1, roleDe: "1-Mana: Vampir + Mana-Quelle",             roleEn: "1-mana: vampire + mana source" },
      { name: "Vicious Conquistador",     count: 1, roleDe: "1-Mana Vampir + Schaden bei Angriff",      roleEn: "1-mana vampire + damage when attacking" },
      { name: "Gifted Aetherborn",        count: 1, roleDe: "2/3 Todesberührung + Lebenspunkte",        roleEn: "2/3 deathtouch + lifelink" },
      { name: "Sorin, Imperious Bloodlord", count: 1, roleDe: "Planeswalker für Vampir-Strategie",      roleEn: "Planeswalker for vampire strategy" },
      { name: "Vampire Nocturnus",        count: 1, roleDe: "Lord: Fliegen + +2/+1 wenn top Karte schwarz", roleEn: "Lord: flying + +2/+1 when top black" },
      { name: "Olivia Voldaren",          count: 1, roleDe: "Macht Gegner-Kreaturen zu Vampiren",       roleEn: "Turns opponent creatures into vampires" },
      { name: "Champion of Dusk",         count: 1, roleDe: "Zieht Karten gleich der Vampir-Anzahl",    roleEn: "Draws cards equal to vampire count" },
      { name: "Bloodline Keeper",         count: 1, roleDe: "Erschafft Vampir-Token jede Runde",        roleEn: "Creates vampire token each turn" },
      { name: "Captivating Vampire",      count: 1, roleDe: "Stiehlt Gegner-Kreatur wenn 5+ Vampire",   roleEn: "Steals opponent creature with 5+ vampires" },
      { name: "Shared Animosity",         count: 1, roleDe: "Alle Angreifer des gleichen Typs +1/+0",   roleEn: "All attackers of same type +1/+0" },
      { name: "Teferi's Protection",      count: 1, roleDe: "Unbesiegbarkeit für das Team",             roleEn: "Invulnerability for the team" },
      { name: "Anguished Unmaking",       count: 1, roleDe: "Entfernt alles außer Ländern",             roleEn: "Removes anything except lands" },
      { name: "Swords to Plowshares",     count: 1, roleDe: "Beste weiße Einzelentfernung",             roleEn: "Best white single removal" },
      { name: "Sol Ring",                 count: 1, roleDe: "Commander-Staple: 2 farbloses Mana",       roleEn: "Commander staple: 2 colorless mana" },
      { name: "Arcane Signet",            count: 1, roleDe: "2 Mana Mana-Stein",                        roleEn: "2-mana mana rock" },
      { name: "Coat of Arms",             count: 1, roleDe: "Alle gleichartigen Kreaturen +X/+X",       roleEn: "All creatures of same type +X/+X" },
    ],
    lands: [
      { name: "Command Tower", count: 1 },
      { name: "Godless Shrine", count: 1 },
      { name: "Blood Crypt", count: 1 },
      { name: "Sacred Foundry", count: 1 },
      { name: "Plains", count: 10 },
      { name: "Swamp", count: 12 },
      { name: "Mountain", count: 12 },
    ],
  },
  {
    key: "cmd-aesi", format: "commander", deckSize: 100,
    commanderSlot: { name: "Aesi, Tyrant of Gyre Strait", count: 1, roleDe: "Commander: spiele zusätzlich Länder, ziehe Karten bei Landfall", roleEn: "Commander: play additional lands, draw on Landfall" },
    labelDe: "Aesi Länder-Kontrolle", labelEn: "Aesi Land Control",
    colors: ["U", "G"], colorHex: "#0e68ab", icon: "earth-outline",
    tagsDe: ["Rampe", "Mittel", "Blau/Grün"], tagsEn: ["Ramp", "Intermediate", "Blue/Green"],
    summaryDe: "Aesi erlaubt es dir jede Runde 2 Länder zu spielen und zieht eine Karte bei jedem Landfall. Ein endloser Strom an Ressourcen.",
    summaryEn: "Aesi lets you play 2 lands each turn and draws a card on each Landfall. An endless stream of resources.",
    whyDe: "Mit Aesi im Spiel: 2 Länder pro Runde = 2 Karten ziehen = mehr Länder finden. Die Maschine läuft von selbst. 'Avenger of Zendikar' erschafft so viele Pflanzen wie Länder im Spiel.",
    whyEn: "With Aesi in play: 2 lands per turn = 2 cards drawn = find more lands. The machine runs itself. 'Avenger of Zendikar' creates plant tokens equal to lands in play.",
    slots: [
      { name: "Cultivate",              count: 1, roleDe: "Holt 2 Länder: sofort + Hand",               roleEn: "Fetches 2 lands: play + hand" },
      { name: "Kodama's Reach",         count: 1, roleDe: "Identisch zu Cultivate",                     roleEn: "Identical to Cultivate" },
      { name: "Exploration",            count: 1, roleDe: "Spiele ein zusätzliches Land",                roleEn: "Play an additional land" },
      { name: "Burgeoning",             count: 1, roleDe: "Spiele Länder im Gegner-Zug auch",            roleEn: "Play lands during opponents' turns too" },
      { name: "Avenger of Zendikar",    count: 1, roleDe: "Erschafft Token gleich Länder-Anzahl",        roleEn: "Creates tokens equal to land count" },
      { name: "Rampant Growth",         count: 1, roleDe: "2-Mana Rampe: holt beliebiges Land",          roleEn: "2-mana ramp: fetches any land" },
      { name: "Tatyova, Benthic Druid", count: 1, roleDe: "Zieht Karten + gewinnt Leben bei Landfall",  roleEn: "Draws cards + gains life on Landfall" },
      { name: "Cyclonic Rift",          count: 1, roleDe: "Beste blaue Massenentfernung: alles zurück",  roleEn: "Best blue board wipe: bounce everything" },
      { name: "Counterspell",           count: 1, roleDe: "Gegenzauber: stoppt wichtige Sprüche",        roleEn: "Counterspell: stops key spells" },
      { name: "Sol Ring",               count: 1, roleDe: "Commander-Staple: 2 farbloses Mana",          roleEn: "Commander staple: 2 colorless mana" },
      { name: "Arcane Signet",          count: 1, roleDe: "2 Mana Mana-Stein",                           roleEn: "2-mana mana rock" },
      { name: "Simic Signet",           count: 1, roleDe: "Simic-Mana-Stein",                            roleEn: "Simic mana rock" },
      { name: "Finale of Devastation",  count: 1, roleDe: "Sucht Kreatur + Massenbuff bei X≥10",         roleEn: "Finds creature + mass buff when X≥10" },
      { name: "Blue Sun's Zenith",      count: 1, roleDe: "Zieht X Karten",                              roleEn: "Draw X cards" },
      { name: "Worldly Counsel",        count: 1, roleDe: "Sucht Kreatur in die Hand",                   roleEn: "Tutors creature to hand" },
      { name: "Simic Growth Chamber",   count: 1, roleDe: "Land das 2 Mana produziert",                  roleEn: "Land that produces 2 mana" },
    ],
    lands: [
      { name: "Command Tower", count: 1 },
      { name: "Breeding Pool", count: 1 },
      { name: "Island", count: 16 },
      { name: "Forest", count: 20 },
    ],
  },
  {
    key: "cmd-rhys", format: "commander", deckSize: 100,
    commanderSlot: { name: "Rhys the Redeemed", count: 1, roleDe: "Commander: erschafft Elfen-Token und verdoppelt alle Token", roleEn: "Commander: creates elf tokens and doubles all tokens" },
    labelDe: "Rhys Token-Verdopplung", labelEn: "Rhys Token Doubling",
    colors: ["W", "G"], colorHex: "#f8d878", icon: "copy-outline",
    tagsDe: ["Token", "Mittel", "Weiß/Grün"], tagsEn: ["Token", "Intermediate", "White/Green"],
    summaryDe: "Rhys verdoppelt für 6 Mana alle Token im Spiel. Mit Verdopplungseffekten wird aus 10 Token schnell 20, dann 40, dann 80. Eine Armee die exponentiell wächst.",
    summaryEn: "Rhys doubles all tokens for 6 mana. With doubling effects, 10 tokens quickly becomes 20, then 40, then 80. An exponentially growing army.",
    whyDe: "'Anointed Procession' verdoppelt alle Token die erschaffen werden. Mit beiden Verdopplern im Spiel werden aus 1 Token 4. 'Triumph of the Hordes' gibt allen Kreaturen Trampel + Infekt — sofortiger Sieg.",
    whyEn: "'Anointed Procession' doubles all tokens created. With both doublers in play, 1 token becomes 4. 'Triumph of the Hordes' gives all creatures trample + infect — instant win.",
    slots: [
      { name: "Anointed Procession",    count: 1, roleDe: "Verdoppelt alle erschaffenen Token",          roleEn: "Doubles all tokens created" },
      { name: "Parallel Lives",         count: 1, roleDe: "Zweiter Verdopplungseffekt",                  roleEn: "Second token doubling effect" },
      { name: "Intangible Virtue",      count: 1, roleDe: "+1/+1 + Vigilanz für alle Token",             roleEn: "+1/+1 + vigilance for all tokens" },
      { name: "Elspeth, Sun's Champion", count: 1, roleDe: "3 Token/Zug + Massenentfernung groß",        roleEn: "3 tokens/turn + mass removal of large" },
      { name: "Secure the Wastes",      count: 1, roleDe: "Sofort X Krieger-Token",                      roleEn: "Flash X warrior tokens" },
      { name: "Triumph of the Hordes",  count: 1, roleDe: "Alle Trampel + Infekt: sofortiger Sieg",      roleEn: "All creatures trample + infect: instant win" },
      { name: "Craterhoof Behemoth",    count: 1, roleDe: "Alle Kreaturen massiv verstärkt + Trampel",   roleEn: "All creatures massively buffed + trample" },
      { name: "Skullclamp",             count: 1, roleDe: "2 Karten ziehen wenn 1/1 stirbt",              roleEn: "Draw 2 cards when a 1/1 dies" },
      { name: "Sylvan Library",         count: 1, roleDe: "Kartenvorteil: sieh 3 Karten/Zug",            roleEn: "Card advantage: see 3 cards/turn" },
      { name: "Chord of Calling",       count: 1, roleDe: "Sucht Kreatur sofort aus Bibliothek",         roleEn: "Instantly tutors creature from library" },
      { name: "Path to Exile",          count: 1, roleDe: "Beste weiße Einzelentfernung",                roleEn: "Best white single removal" },
      { name: "Sol Ring",               count: 1, roleDe: "Commander-Staple: 2 farbloses Mana",          roleEn: "Commander staple: 2 colorless mana" },
      { name: "Arcane Signet",          count: 1, roleDe: "2 Mana Mana-Stein",                           roleEn: "2-mana mana rock" },
      { name: "Selesnya Signet",        count: 1, roleDe: "Selesnya-Mana-Stein",                         roleEn: "Selesnya mana rock" },
      { name: "Gavony Township",        count: 1, roleDe: "Alle Kreaturen +1/+1 Zähler für Mana",        roleEn: "All creatures +1/+1 counter for mana" },
      { name: "Trostani, Selesnya's Voice", count: 1, roleDe: "Lebenspunkte bei Token + Bevölkern",      roleEn: "Life on token + populate" },
    ],
    lands: [
      { name: "Command Tower", count: 1 },
      { name: "Temple Garden", count: 1 },
      { name: "Gavony Township", count: 1 },
      { name: "Plains", count: 18 },
      { name: "Forest", count: 17 },
    ],
  },
];

// ─── Pioneer Archetypes ────────────────────────────────────────────────────

const PIONEER_ARCHETYPES: Archetype[] = [
  {
    key: "pio-rakdos", format: "pioneer", deckSize: 60,
    labelDe: "Rakdos Midrange (Pioneer)", labelEn: "Rakdos Midrange (Pioneer)",
    colors: ["B", "R"], colorHex: "#d3202a", icon: "skull-outline",
    tagsDe: ["Midrange", "Fortgeschritten", "Schwarz/Rot"], tagsEn: ["Midrange", "Advanced", "Black/Red"],
    summaryDe: "Das dominante Pioneer-Deck. Handstörung, Entfernung und Kreaturen mit hohem Kartenwert zermürben jeden Gegner systematisch.",
    summaryEn: "The dominant Pioneer deck. Hand disruption, removal, and high-value creatures systematically grind down any opponent.",
    whyDe: "'Thoughtseize' entfernt die gefährlichste Karte aus der Gegnerhand. 'Fable of the Mirror-Breaker' erschafft Token, rüstet um und transformiert zu einer starken Kreatur. 'Sheoldred' macht jeden Zug des Gegners schmerzhafter.",
    whyEn: "'Thoughtseize' removes the most dangerous card from the opponent's hand. 'Fable of the Mirror-Breaker' creates tokens, loots, and transforms. 'Sheoldred' makes every opponent draw painful.",
    slots: [
      { name: "Thoughtseize",                count: 4, roleDe: "Kern-Handstörer: entfernt beste Karte",     roleEn: "Core hand disruptor: removes best card" },
      { name: "Fatal Push",                  count: 4, roleDe: "Beste schwarze Einzelentfernung",           roleEn: "Best black single removal" },
      { name: "Fable of the Mirror-Breaker", count: 4, roleDe: "Vielseitig: Token + Rüsten + Kreatur",      roleEn: "Versatile: token + loot + creature" },
      { name: "Bonecrusher Giant",           count: 4, roleDe: "Entfernung + 4/3 Kreatur in einer Karte",   roleEn: "Removal + 4/3 creature in one card" },
      { name: "Sheoldred, the Apocalypse",   count: 4, roleDe: "Lebensgewinn + Schaden: dominiert Midrange", roleEn: "Life gain + damage: dominates midrange" },
      { name: "Graveyard Trespasser",        count: 4, roleDe: "Friedhof-Hate + schwer zu entfernen",       roleEn: "Graveyard hate + hard to remove" },
      { name: "Kalitas, Traitor of Ghet",    count: 3, roleDe: "Verhindert Wiedergeburt + Token",           roleEn: "Prevents recursion + tokens" },
      { name: "Kolaghan's Command",          count: 3, roleDe: "Mehrzweck: Entfernung + Karte + Artefakt",  roleEn: "Multi-mode: removal + card + artifact" },
      { name: "Lolth, Spider Queen",         count: 2, roleDe: "Planeswalker: Token + Karten ziehen",       roleEn: "Planeswalker: tokens + card draw" },
    ],
    lands: [
      { name: "Blood Crypt", count: 4 },
      { name: "Swamp", count: 10 },
      { name: "Mountain", count: 10 },
    ],
  },
  {
    key: "pio-azorius-kontrolle", format: "pioneer", deckSize: 60,
    labelDe: "Azorius Kontrolle (Pioneer)", labelEn: "Azorius Control (Pioneer)",
    colors: ["W", "U"], colorHex: "#0e68ab", icon: "water-outline",
    tagsDe: ["Kontrolle", "Fortgeschritten", "Weiß/Blau"], tagsEn: ["Control", "Advanced", "White/Blue"],
    summaryDe: "Typische Kontroll-Strategie: Gegenzauber, Entfernung und Massenentfernung halten das Spiel unter Kontrolle. Shark Typhoon und Teferi gewinnen das Spiel.",
    summaryEn: "Classic control strategy: counterspells, removal, and board wipes keep the game under control. Shark Typhoon and Teferi win the game.",
    whyDe: "'Supreme Verdict' kann nicht durch Gegenzauber gestoppt werden — perfekte Massenentfernung. 'Teferi, Hero of Dominaria' ist der stärkste Planeswalker im Format.",
    whyEn: "'Supreme Verdict' cannot be countered — perfect mass removal. 'Teferi, Hero of Dominaria' is the strongest planeswalker in the format.",
    slots: [
      { name: "Counterspell",                count: 4, roleDe: "Kern-Gegenzauber",                          roleEn: "Core counterspell" },
      { name: "Absorb",                      count: 4, roleDe: "Gegenzauber + 3 Leben gewinnen",            roleEn: "Counterspell + gain 3 life" },
      { name: "Supreme Verdict",             count: 4, roleDe: "Unkonterbare Massenentfernung",             roleEn: "Uncounterable board wipe" },
      { name: "Teferi, Hero of Dominaria",   count: 4, roleDe: "Planeswalker: zieht + räumt auf + sperrt", roleEn: "Planeswalker: draws + removes + locks" },
      { name: "Shark Typhoon",               count: 3, roleDe: "Sofort-Hai-Token + Gegenzauber-Ersatz",    roleEn: "Flash shark token + counterspell replacement" },
      { name: "Memory Deluge",               count: 4, roleDe: "Karten-Qualität: 4 Karten auf 2",          roleEn: "Card quality: 4 cards to choose 2" },
      { name: "Settle the Wreckage",         count: 3, roleDe: "Sofort-Massenentfernung bei Angriff",       roleEn: "Flash board wipe on attack" },
      { name: "March of Otherworldly Light", count: 3, roleDe: "Flexible Entfernung: exiliert alles",       roleEn: "Flexible exile removal for anything" },
      { name: "Elspeth, Sun's Nemesis",      count: 3, roleDe: "Gewinn-Bedingung + Lebensgewinn",          roleEn: "Win condition + life gain" },
    ],
    lands: [
      { name: "Hallowed Fountain", count: 4 },
      { name: "Glacial Fortress", count: 4 },
      { name: "Plains", count: 8 },
      { name: "Island", count: 8 },
    ],
  },
  {
    key: "pio-elfen", format: "pioneer", deckSize: 60,
    labelDe: "Elfen-Kombo (Pioneer)", labelEn: "Elf Combo (Pioneer)",
    colors: ["G"], colorHex: "#16a34a", icon: "leaf-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Grün"], tagsEn: ["Combo", "Advanced", "Green"],
    summaryDe: "Pioneer-Elfen ist eine Kombo-Maschine. Das Deck kann in Runde 3-4 mit Craterhoof-Behemoth gewinnen, indem es Mana-Elfen nutzt.",
    summaryEn: "Pioneer Elves is a combo machine. The deck can win on turn 3-4 with Craterhoof Behemoth by using mana elves to cast more elves and finally Craterhoof.",
    whyDe: "Der Ablauf: T1 Llanowar Elves, T2 Elvish Archdruid oder Dwynen's Elite, T3 mit 4-5 Mana: Collected Company findet 2 Elfen, T4 mit 8+ Mana: Craterhoof Behemoth gewinnt sofort.",
    whyEn: "The sequence: T1 Llanowar Elves, T2 Elvish Archdruid or Dwynen's Elite, T3 with 4-5 mana: Collected Company finds 2 elves, T4 with 8+ mana: Craterhoof Behemoth wins immediately.",
    slots: [
      { name: "Llanowar Elves",         count: 4, roleDe: "T1-Rampe: Elfenmana-Basis",                 roleEn: "T1 ramp: elf mana base" },
      { name: "Elvish Mystic",          count: 4, roleDe: "Zweiter Satz T1-Rampe",                     roleEn: "Second set of T1 ramp" },
      { name: "Elvish Archdruid",       count: 4, roleDe: "Lord + Mana für alle Elfen",                roleEn: "Lord + mana for all elves" },
      { name: "Dwynen's Elite",         count: 4, roleDe: "Erschafft Token wenn Elf schon da",         roleEn: "Creates token if elf already in play" },
      { name: "Collected Company",      count: 4, roleDe: "Sofort: 2 Kreaturen bis CMC 3",             roleEn: "Flash: 2 creatures up to CMC 3" },
      { name: "Chord of Calling",       count: 4, roleDe: "Sucht Craterhoof oder anderen Schlüsselelf", roleEn: "Finds Craterhoof or key elf" },
      { name: "Ezuri, Renegade Leader", count: 3, roleDe: "Lord: pumpt alle Elfen für Massenangriff",  roleEn: "Lord: pumps all elves for alpha strike" },
      { name: "Craterhoof Behemoth",    count: 2, roleDe: "Gewinn-Bedingung: alle Kreaturen riesig",   roleEn: "Win condition: all creatures giant" },
      { name: "Regal Force",            count: 1, roleDe: "Zieht für jeden grünen Kreatur",            roleEn: "Draws for each green creature" },
    ],
    lands: [
      { name: "Nykthos, Shrine to Nyx", count: 4 },
      { name: "Forest", count: 20 },
    ],
  },
  {
    key: "pio-mono-weiss", format: "pioneer", deckSize: 60,
    labelDe: "Mono-Weiß Hingabe (Pioneer)", labelEn: "Mono-White Devotion (Pioneer)",
    colors: ["W"], colorHex: "#f8d878", icon: "shield-checkmark-outline",
    tagsDe: ["Midrange", "Mittel", "Weiß"], tagsEn: ["Midrange", "Intermediate", "White"],
    summaryDe: "Mono-Weiß nutzt Hingabe an Weiß für 'Nykthos'. Mit genug weißen Symbolen produziert Nykthos massenhaft Mana für große Sprüche.",
    summaryEn: "Mono-White uses devotion to White for 'Nykthos'. With enough white symbols, Nykthos produces massive mana for big spells.",
    whyDe: "'Nykthos, Shrine to Nyx' produziert Mana gleich der weißen Hingabe. Mit 5 weißen Symbolen = 5 weißes Mana für 2 Mana Investition. Das Deck stapelt günstige weiße Kreaturen um die Hingabe aufzubauen.",
    whyEn: "'Nykthos, Shrine to Nyx' produces mana equal to white devotion. With 5 white symbols = 5 white mana for 2 mana investment. The deck stacks cheap white creatures to build devotion.",
    slots: [
      { name: "Hallowed Haunting",       count: 4, roleDe: "Enchantment-Kreatur-Motor",                  roleEn: "Enchantment creature engine" },
      { name: "Thassa's Oracle",         count: 4, roleDe: "Gewinn-Bedingung: leere Bibliothek",         roleEn: "Win condition: empty library" },
      { name: "Spirited Companion",      count: 4, roleDe: "1-Mana: Karte ziehen + Enchantment",         roleEn: "1-mana: draw card + enchantment" },
      { name: "Hateful Eidolon",         count: 4, roleDe: "Karten-Zieher bei Todesberührung-Toden",     roleEn: "Card draw on deathtouch deaths" },
      { name: "Sram, Senior Edificer",   count: 4, roleDe: "Zieht Karte bei jedem Aura/Ausrüstung",      roleEn: "Draws card for each aura/equipment" },
      { name: "Eidolon of Countless Battles", count: 4, roleDe: "Wächst mit Auren und Kreaturen",        roleEn: "Grows with auras and creatures" },
      { name: "Heliod, Sun-Crowned",     count: 4, roleDe: "Gibt +1/+1-Zähler bei Lebensgewinn",         roleEn: "Adds +1/+1 counter on life gain" },
      { name: "Staggering Insight",      count: 4, roleDe: "Aura: Fliegen + Karten ziehen + Leben",      roleEn: "Aura: flying + card draw + life" },
    ],
    lands: [
      { name: "Nykthos, Shrine to Nyx", count: 4 },
      { name: "Plains", count: 20 },
    ],
  },
  {
    key: "pio-phoenix", format: "pioneer", deckSize: 60,
    labelDe: "Izzet Phönix (Pioneer)", labelEn: "Izzet Phoenix (Pioneer)",
    colors: ["U", "R"], colorHex: "#e67e22", icon: "flame-outline",
    tagsDe: ["Graveyard", "Fortgeschritten", "Blau/Rot"], tagsEn: ["Graveyard", "Advanced", "Blue/Red"],
    summaryDe: "Arclight Phoenix kehrt aus dem Friedhof zurück wenn du 3 Sprüche in einem Zug wirkst. Das Deck nutzt diesen Motor für unendliche Bedrohungen.",
    summaryEn: "Arclight Phoenix returns from the graveyard when you cast 3 spells in a turn. The deck uses this engine for endless threats.",
    whyDe: "Der Plan: Arclight Phoenix in den Friedhof legen (per Faithless Looting, Consider), dann T3 drei 1-Mana-Sprüche wirken und Arclight kehrt kostenlos zurück. Mit 4 Phoenix im Deck hat man 4 Bedrohungen die immer wieder kommen.",
    whyEn: "The plan: put Arclight Phoenix in the graveyard, then cast 3 one-mana spells on T3 and Arclight returns for free. With 4 phoenixes, you have 4 threats that always come back.",
    slots: [
      { name: "Arclight Phoenix",        count: 4, roleDe: "Kern-Bedrohung: kehrt kostenlos zurück",     roleEn: "Core threat: returns for free" },
      { name: "Faithless Looting",       count: 4, roleDe: "Legt Phoenix in Friedhof + zieht Karten",    roleEn: "Puts Phoenix in graveyard + draws cards" },
      { name: "Consider",                count: 4, roleDe: "Skrying + legt Karte in Friedhof",           roleEn: "Scry + puts card in graveyard" },
      { name: "Opt",                     count: 4, roleDe: "1-Mana: Skrying + Karte ziehen",             roleEn: "1-mana: scry + draw card" },
      { name: "Pieces of the Puzzle",    count: 4, roleDe: "Findet 2 Zaubersprüche aus 5 Karten",        roleEn: "Finds 2 spells from top 5" },
      { name: "Temporal Trespass",       count: 2, roleDe: "Extra-Zug: oft für 3 Mana mit Delirium",     roleEn: "Extra turn: often 3 mana with delirium" },
      { name: "Saheeli, Sublime Artificer", count: 3, roleDe: "Token für jeden Spruch + Kopier-Fähigkeit", roleEn: "Token for each spell + copy ability" },
      { name: "Thing in the Ice",        count: 4, roleDe: "Verwandelt sich in 7/8 Horror: bounct alles", roleEn: "Transforms into 7/8 horror: bounces all" },
      { name: "Lightning Axe",           count: 3, roleDe: "5 Schaden für 1 Mana (wirft Karte ab)",      roleEn: "5 damage for 1 mana (discards card)" },
    ],
    lands: [
      { name: "Steam Vents", count: 4 },
      { name: "Spirebluff Canal", count: 4 },
      { name: "Island", count: 8 },
      { name: "Mountain", count: 8 },
    ],
  },
];

// ─── Pauper Archetypes ─────────────────────────────────────────────────────

const PAUPER_ARCHETYPES: Archetype[] = [
  {
    key: "pau-brand", format: "pauper", deckSize: 60,
    labelDe: "Pauper Brand", labelEn: "Pauper Burn",
    colors: ["R"], colorHex: "#e67e22", icon: "flame-outline",
    tagsDe: ["Aggro", "Einfach", "Rot", "Budget"], tagsEn: ["Aggro", "Beginner", "Red", "Budget"],
    summaryDe: "Günstigstes Burn-Deck überhaupt. Alle Karten sind Commons. Chain Lightning, Lava Spike und Goblin Guide für 3-4 Mana pro Kopf.",
    summaryEn: "Cheapest burn deck ever. All cards are commons. Chain Lightning, Lava Spike, and Goblin Guide for a few dollars each.",
    whyDe: "In Pauper kosten die mächtigsten Brand-Karten wie 'Chain Lightning' nur wenige Cent. Das Deck ist extrem günstig aufzubauen aber konkurrenzfähig auf dem Level. 'Keldon Marauders' verursacht garantiert 3 Schaden.",
    whyEn: "In Pauper, the most powerful burn cards like 'Chain Lightning' cost just a few cents. The deck is extremely cheap to build but competitive at that level. 'Keldon Marauders' guarantees 3 damage.",
    slots: [
      { name: "Chain Lightning",      count: 4, roleDe: "3 Schaden für 1 Mana (kopierbar)",          roleEn: "3 damage for 1 mana (copyable)" },
      { name: "Lava Spike",           count: 4, roleDe: "3 Direktschaden immer ans Gesicht",         roleEn: "3 direct damage always to face" },
      { name: "Rift Bolt",            count: 4, roleDe: "3 Schaden: aufgesetzt für 1 Mana",          roleEn: "3 damage: suspend for 1 mana" },
      { name: "Shard Volley",         count: 4, roleDe: "4 Schaden für 1 Mana (Kosten: 1 Land)",     roleEn: "4 damage for 1 mana (cost: 1 land)" },
      { name: "Goblin Guide",         count: 4, roleDe: "1-Mana 2/2 Hast (common in Pauper)",        roleEn: "1-mana 2/2 haste (common in Pauper)" },
      { name: "Monastery Swiftspear", count: 4, roleDe: "Prowess + Hast wächst mit Sprüchen",        roleEn: "Prowess + haste grows with spells" },
      { name: "Keldon Marauders",     count: 4, roleDe: "Verursacht garantiert 3 Schaden",           roleEn: "Guaranteed 3 damage" },
      { name: "Needle Drop",          count: 4, roleDe: "1 Schaden + Karte ziehen für 1 Mana",       roleEn: "1 damage + draw a card for 1 mana" },
    ],
    lands: [{ name: "Mountain", count: 20 }],
  },
  {
    key: "pau-elfen", format: "pauper", deckSize: 60,
    labelDe: "Pauper Elfen", labelEn: "Pauper Elves",
    colors: ["G"], colorHex: "#16a34a", icon: "leaf-outline",
    tagsDe: ["Kombo", "Mittel", "Grün", "Budget"], tagsEn: ["Combo", "Intermediate", "Green", "Budget"],
    summaryDe: "Pauper Elfen nutzt Nettle Sentinel + Heritage Druid für unendliches Mana. Dann Grapeshot für sofortigen Sieg oder Elvish Vanguard als Riesenmonster.",
    summaryEn: "Pauper Elves uses Nettle Sentinel + Heritage Druid for infinite mana. Then Grapeshot for instant win or Elvish Vanguard as a huge monster.",
    whyDe: "Die Kombo: 3 Elfen tappen für Heritage Druid → 3 grünes Mana. Einen Elfen für 1 Mana spielen → Nettle Sentinels werden untapped → wiederholen. Das erzeugt theoretisch unendliches Mana.",
    whyEn: "The combo: tap 3 elves for Heritage Druid → 3 green mana. Cast an elf for 1 mana → Nettle Sentinels untap → repeat. This theoretically generates infinite mana. Finally: Grapeshot for X damage.",
    slots: [
      { name: "Llanowar Elves",     count: 4, roleDe: "1-Mana Rampe-Elfe",                       roleEn: "1-mana ramp elf" },
      { name: "Elvish Mystic",      count: 4, roleDe: "Zweiter Satz 1-Mana Rampe",                roleEn: "Second set of 1-mana ramp" },
      { name: "Nettle Sentinel",    count: 4, roleDe: "Kern-Kombo: enttappt bei grünen Sprüchen", roleEn: "Core combo: untaps with green spells" },
      { name: "Heritage Druid",     count: 4, roleDe: "Kern-Kombo: Mana aus getappten Elfen",     roleEn: "Core combo: mana from tapped elves" },
      { name: "Elvish Vanguard",    count: 4, roleDe: "Wächst mit jeder gespielten Elfe",         roleEn: "Grows with each elf played" },
      { name: "Wellwisher",         count: 4, roleDe: "Lebenspunkte für Elfen: Aggro-Gegenmaßnahme", roleEn: "Life for elves: aggro counter" },
      { name: "Timberwatch Elf",    count: 4, roleDe: "Lord: gibt einem Elfen riesige Boni",      roleEn: "Lord: gives one elf huge bonuses" },
      { name: "Lead the Stampede",  count: 4, roleDe: "Zieht bis zu 5 Kreaturen",                 roleEn: "Draws up to 5 creatures" },
      { name: "Grapeshot",          count: 4, roleDe: "Storm: X Schaden bei Endlos-Kombo",        roleEn: "Storm: X damage on infinite combo" },
    ],
    lands: [{ name: "Forest", count: 20 }],
  },
  {
    key: "pau-affinity", format: "pauper", deckSize: 60,
    labelDe: "Pauper Affinity", labelEn: "Pauper Affinity",
    colors: ["U", "R"], colorHex: "#0e68ab", icon: "construct-outline",
    tagsDe: ["Kombo", "Fortgeschritten", "Blau/Rot", "Budget"], tagsEn: ["Combo", "Advanced", "Blue/Red", "Budget"],
    summaryDe: "Affinity für Artefakte: Kreaturen kosten Mana gleich der Nicht-Artefakt-Länder im Spiel. Mit vielen Artefakten spielst du Kreaturen kostenlos.",
    summaryEn: "Affinity for artifacts: creatures cost mana equal to non-artifact lands in play. With many artifacts, you play creatures for free.",
    whyDe: "'Frogmite' und 'Myr Enforcer' haben Affinity für Artefakte — mit 4+ Artefakten kostet Frogmite 0 Mana. 'Cranial Plating' gibt +X/+0 gleich der Artefakt-Anzahl — oft +8-10.",
    whyEn: "'Frogmite' and 'Myr Enforcer' have affinity for artifacts — with 4+ artifacts, Frogmite costs 0 mana. 'Cranial Plating' gives +X/+0 equal to artifact count — often +8-10.",
    slots: [
      { name: "Frogmite",          count: 4, roleDe: "4/4 kostenlos mit Affinity",               roleEn: "4/4 for free with affinity" },
      { name: "Myr Enforcer",      count: 4, roleDe: "4/4 für 0-1 Mana mit Affinity",            roleEn: "4/4 for 0-1 mana with affinity" },
      { name: "Thoughtcast",       count: 4, roleDe: "2 Karten ziehen für 1 Mana mit Affinity",  roleEn: "Draw 2 cards for 1 mana with affinity" },
      { name: "Cranial Plating",   count: 4, roleDe: "+X/+0 gleich Artefakt-Anzahl",              roleEn: "+X/+0 equal to artifact count" },
      { name: "Atog",              count: 4, roleDe: "Wächst durch Artefakt-Opfer",               roleEn: "Grows by sacrificing artifacts" },
      { name: "Springleaf Drum",   count: 4, roleDe: "Günstige Mana-Artefakt-Produktion",        roleEn: "Cheap mana artifact production" },
      { name: "Chromatic Star",    count: 4, roleDe: "Billiges Artefakt + zieht Karte beim Opfern", roleEn: "Cheap artifact + draws card when sacrificed" },
      { name: "Seat of the Synod", count: 4, roleDe: "Artefakt-Land für Affinity",               roleEn: "Artifact land for affinity" },
      { name: "Lightning Bolt",    count: 4, roleDe: "Entfernung + Brand",                        roleEn: "Removal + burn" },
    ],
    lands: [
      { name: "Seat of the Synod", count: 4 },
      { name: "Great Furnace", count: 4 },
      { name: "Island", count: 6 },
      { name: "Mountain", count: 6 },
    ],
  },
  {
    key: "pau-dimir-faeries", format: "pauper", deckSize: 60,
    labelDe: "Dimir Faeries (Pauper)", labelEn: "Dimir Faeries (Pauper)",
    colors: ["U", "B"], colorHex: "#7c3aed", icon: "sparkles-outline",
    tagsDe: ["Kontrolle", "Fortgeschritten", "Blau/Schwarz", "Budget"], tagsEn: ["Control", "Advanced", "Blue/Black", "Budget"],
    summaryDe: "Dimir Faeries ist das stärkste Kontrolldeck in Pauper. Günstige Sofort-Faeries + Gegenzauber halten den Gegner in Schach.",
    summaryEn: "Dimir Faeries is the strongest control deck in Pauper. Cheap flash faeries + counterspells keep the opponent in check.",
    whyDe: "'Spellstutter Sprite' ist eine Sofort-Faerie die einen Spruch kontert deren Manakosten der Faerie-Anzahl entsprechen. 'Snuff Out' zerstört für 0 Mana.",
    whyEn: "'Spellstutter Sprite' is a flash faerie that counters a spell with mana cost equal to faerie count. 'Snuff Out' destroys for 0 mana.",
    slots: [
      { name: "Spellstutter Sprite", count: 4, roleDe: "Sofort-Faerie + bedingter Gegenzauber",   roleEn: "Flash faerie + conditional counterspell" },
      { name: "Faerie Miscreant",    count: 4, roleDe: "1-Mana-Faerie: zieht Karte wenn zweite da", roleEn: "1-mana faerie: draws card with another" },
      { name: "Counterspell",        count: 4, roleDe: "Zählt alles für 2 Mana",                   roleEn: "Counters anything for 2 mana" },
      { name: "Snap",                count: 4, roleDe: "Gibt Mana zurück + Kreatur-Bounce",         roleEn: "Refunds mana + creature bounce" },
      { name: "Snuff Out",           count: 4, roleDe: "Zerstört für 0 Mana (4 Leben Kosten)",      roleEn: "Destroys for 0 mana (4 life cost)" },
      { name: "Brainstorm",          count: 4, roleDe: "Karten-Qualität: sieh 3 Karten",            roleEn: "Card quality: see 3 cards" },
      { name: "Preordain",           count: 4, roleDe: "Bibliotheks-Manipulation + Scrying",        roleEn: "Library manipulation + scrying" },
      { name: "Gurmag Angler",       count: 4, roleDe: "5/5 für 1 Mana mit Friedhof-Kosten",        roleEn: "5/5 for 1 mana with graveyard cost" },
      { name: "Drown in the Loch",   count: 4, roleDe: "Entfernung + Gegenzauber in einer Karte",   roleEn: "Removal + counterspell in one card" },
    ],
    lands: [
      { name: "Dismal Backwater", count: 4 },
      { name: "Island", count: 10 },
      { name: "Swamp", count: 10 },
    ],
  },
];

// ─── Registry ──────────────────────────────────────────────────────────────

export function getArchetypesByFormat(format: string): Archetype[] {
  switch (format) {
    case "standard":  return STANDARD_ARCHETYPES;
    case "commander": return COMMANDER_ARCHETYPES;
    case "pioneer":   return PIONEER_ARCHETYPES;
    case "pauper":    return PAUPER_ARCHETYPES;
    case "modern":
    default:          return MODERN_ARCHETYPES;
  }
}

export function findArchetype(key: string, format: string): Archetype | undefined {
  return getArchetypesByFormat(format).find((a) => a.key === key);
}
