// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CardAnimation.tsx": () => import("../components/mockups/CardAnimation.tsx"),
  "./components/mockups/mtg-website-variants/Cinematic.tsx": () => import("../components/mockups/mtg-website-variants/Cinematic.tsx"),
  "./components/mockups/mtg-website-variants/Editorial.tsx": () => import("../components/mockups/mtg-website-variants/Editorial.tsx"),
  "./components/mockups/mtg-website-variants/Grimoire.tsx": () => import("../components/mockups/mtg-website-variants/Grimoire.tsx"),
  "./components/mockups/mtg-design-variants/ArcaneBlueprint.tsx": () => import("../components/mockups/mtg-design-variants/ArcaneBlueprint.tsx"),
  "./components/mockups/mtg-design-variants/Arena.tsx": () => import("../components/mockups/mtg-design-variants/Arena.tsx"),
  "./components/mockups/mtg-design-variants/Codex.tsx": () => import("../components/mockups/mtg-design-variants/Codex.tsx"),
  "./components/mockups/mtg-design-variants/Grimoire.tsx": () => import("../components/mockups/mtg-design-variants/Grimoire.tsx"),
  "./components/mockups/mtg-design-variants/MysticForest.tsx": () => import("../components/mockups/mtg-design-variants/MysticForest.tsx"),
  "./components/mockups/mtg-design-variants/NeonMana.tsx": () => import("../components/mockups/mtg-design-variants/NeonMana.tsx")
};
