// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CardAnimation.tsx": () => import("../components/mockups/CardAnimation.tsx"),
  "./components/mockups/mtg-design-variants/Arena.tsx": () => import("../components/mockups/mtg-design-variants/Arena.tsx"),
  "./components/mockups/mtg-design-variants/Codex.tsx": () => import("../components/mockups/mtg-design-variants/Codex.tsx"),
  "./components/mockups/mtg-design-variants/Grimoire.tsx": () => import("../components/mockups/mtg-design-variants/Grimoire.tsx")
};
